import type { SingaporeStatuteRule } from './types';export const CPF_STATUTE_RULES: Record<string, SingaporeStatuteRule> = {  // -------------------------------------------------------------
  CPF_WAGE_CEILINGS_2026: {
    id: 'CPF_WAGE_CEILINGS_2026',
    authority: 'CPF',
    authorityName: 'Central Provident Fund Board (CPF)',
    sourcePublisher: 'Singapore Statutes Online / AGC',
    legalOrStandardInstrument: 'Central Provident Fund Act 1953',
    actTitle: 'Central Provident Fund Act 1953',
    actCode: 'CPFA1953',
    sectionOrSchedule: 'First Schedule',
    ruleTitle: 'Ordinary Wage (OW) Monthly Ceiling ($8,000 in 2026) & Additional Wage (AW) Ceiling',
    category: 'CPF_PAYROLL',
    principle: 'CPF contributions are payable on Ordinary Wages (OW) up to the statutory monthly wage ceiling, and on Additional Wages (AW) up to the annual ceiling formula.',
    verbatimStatuteText: 'Every employer of an employee who is a citizen of Singapore or a permanent resident shall pay to the Fund monthly contributions at the statutory rates up to the Ordinary Wage monthly ceiling of $8,000, and up to the Additional Wage annual ceiling calculated as $102,000 minus total Ordinary Wages subject to CPF in the year.',
    application: 'Payroll calculations for Singapore Citizen and Permanent Resident employees.',
    practicalRules: [
      '2026 Ordinary Wage (OW) Ceiling: SGD 8,000 per month (effective 1 January 2026). Mandatory CPF is capped at SGD 8,000 of monthly basic salary.',
      'Historical Phased Ceilings: SGD 6,000 (pre-Sept 2023) -> SGD 6,800 (Jan 2024) -> SGD 7,400 (Jan 2025) -> SGD 8,000 (1 Jan 2026).',
      'Additional Wage (AW) Ceiling Formula: $$\\text{AW Ceiling} = \\text{SGD 102,000} - \\text{Total OW subject to CPF in the year}$$.',
      'Contribution Rates (Age $\\le 55$): Employer 17%, Employee 20% (Total 37%). For SGD 8,000 salary: Employer = SGD 1,360, Employee = SGD 1,600 (Total = SGD 2,960).',
      'Due Date: CPF contributions are due at the end of the calendar month and must be paid by the 14th of the following month.'
    ],
    canonicalUrl: 'https://www.cpf.gov.sg/employer/employer-obligations/how-much-cpf-contributions-to-pay',
    tags: ['cpf ceiling', 'ordinary wage ceiling', 'wage ceiling', '2026 cpf', 'cpf ceiling 2026', '8000 ceiling', 'ow ceiling 8000', 'aw ceiling', 'cpf contribution', 'monthly contribution rate', 'ordinary wage 8000', 'cpf rates 2026'],
    sourceStatus: 'VERIFIED',
    sourceType: 'AUTHORITATIVE_SOURCE',
    evidenceTier: 'PRIMARY_SOURCE',
    isVerbatimText: true,
    effectiveDate: '2026-01-01',
    validFrom: '2026-01-01',
    lastVerifiedDate: '2026-09-01',
    reviewAuditCycleDays: 365
  },

  CPF_SDL_SKILLS_DEVELOPMENT_LEVY: {
    id: 'CPF_SDL_SKILLS_DEVELOPMENT_LEVY',
    authority: 'CPF',
    authorityName: 'SkillsFuture Singapore & CPF Board',
    actTitle: 'Skills Development Levy Act 1979',
    actCode: 'SDLA1979',
    sectionOrSchedule: 'Section 3',
    ruleTitle: 'Skills Development Levy (SDL) Calculation Formula (0.25%, Min $2, Max $11.25)',
    category: 'CPF_PAYROLL',
    principle: 'Employers must pay a monthly Skills Development Levy (SDL) for all employees rendering services in Singapore, collected by the CPF Board on behalf of SkillsFuture Singapore.',
    application: 'Calculated monthly alongside payroll and submitted together with monthly CPF returns.',
    practicalRules: [
      'Levy Rate: 0.25% of the total monthly remuneration of each employee.',
      'Minimum Monthly Cap: Minimum SGD 2.00 per employee earning less than SGD 800.',
      'Maximum Monthly Cap: Maximum SGD 11.25 per employee earning SGD 4,500 and above (0.25% of SGD 4,500).',
      'Applies to: All employees (Singapore Citizens, PRs, and foreign work pass holders [EP, S-Pass, Work Permit]).',
      'Tax Treatment: Employer SDL is an allowable business operating expense under Section 14 of the Income Tax Act.'
    ],
    canonicalUrl: 'https://www.cpf.gov.sg/employer/employer-obligations/skills-development-levy',
    tags: ['sdl', 'skills development levy', 'sdl formula', 'max 11.25', 'min 2.00']
  },

  CPF_EMPLOYER_TAX_DEDUCTIBILITY: {
    id: 'CPF_EMPLOYER_TAX_DEDUCTIBILITY',
    authority: 'IRAS',
    authorityName: 'Inland Revenue Authority of Singapore (IRAS) & AGC',
    actTitle: 'Income Tax Act 1947',
    actCode: 'ITA1947',
    sectionOrSchedule: 'Section 14(1)(e)',
    ruleTitle: 'Tax Deductibility of Statutory Employer CPF Contributions',
    category: 'TAX_INCOME',
    principle: 'Mandatory employer contributions made in respect of an employee to the CPF pursuant to the CPF Act are allowable as deductions in determining taxable corporate profit.',
    application: 'Company claims full tax deduction for the 17% employer CPF expense in P&L.',
    practicalRules: [
      'Mandatory CPF: Fully deductible up to the statutory limits (OW ceiling SGD 8,000 / AW ceiling formula).',
      'Voluntary CPF / Excess Contributions: Any employer CPF contribution exceeding the statutory ceiling is non-deductible for the employer and is taxable income in the hands of the employee.',
      'Self-Employed / Working Directors: Working directors who are employees of the company receive tax-deductible employer CPF under Section 14(1)(e).'
    ],
    canonicalUrl: 'https://sso.agc.gov.sg/Act/ITA1947?ProvIds=P15-#pr14-',
    tags: ['cpf tax deduction', 'section 14(1)(e)', 'employer cpf', 'voluntary cpf']
  },

  CPFA_SEC7_FIRST_SCHEDULE: {
    id: 'CPFA_SEC7_FIRST_SCHEDULE',
    authority: 'CPF',
    authorityName: 'Central Provident Fund Board (CPF)',
    sourcePublisher: 'Singapore Statutes Online / AGC',
    legalOrStandardInstrument: 'Central Provident Fund Act 1953',
    actTitle: 'Central Provident Fund Act 1953',
    actCode: 'CPFA1953',
    sectionOrSchedule: 'Section 7 & First Schedule',
    ruleTitle: 'Statutory CPF Contribution Rates & Rounding Rules (Cents Discarded for Employee, Dollar Rounding for Employer)',
    category: 'CPF_PAYROLL',
    principle: 'Under Section 7 and the First Schedule of the Central Provident Fund Act 1953, the employer pays both employer and employee contributions. The employee share is deducted from wages with cents discarded. The total contribution is rounded to the nearest dollar, and employer contribution is the difference between total and employee contribution.',
    verbatimStatuteText: 'Every employer of an employee shall pay monthly to the Fund in respect of each employee contributions at the respective rates prescribed in the First Schedule. In calculating the employee\'s share of contribution, any fraction of a dollar which is a cent or cents shall be discarded. Total contribution payable shall be rounded to the nearest dollar.',
    application: 'Calculation of monthly employee and employer CPF contributions up to the Ordinary Wage monthly ceiling (SGD 8,000 for 2026).',
    practicalRules: [
      'Employee CPF Share: For age 55 and below, 20% of Ordinary Wages. Statutory Rounding: Cents are discarded / dropped.',
      'Employer CPF Share: For age 55 and below, 17% of Ordinary Wages. Rounding: Total CPF rounded to nearest dollar; Employer CPF = Total CPF - Employee CPF.',
      'Ordinary Wage (OW) Ceiling: SGD 8,000 per month effective 1 January 2026.',
      'Tax Deductibility: Mandatory employer CPF is 100% tax-deductible under Section 14(1)(e) of the Income Tax Act 1947.'
    ],
    canonicalUrl: 'https://sso.agc.gov.sg/Act/CPFA1953?ProvIds=P12-#pr7-',
    tags: ['cpf act section 7', 'first schedule', 'cpf rounding', 'employee cpf 20%', 'employer cpf 17%', 'cpf calculation', 'cents discarded'],
    sourceStatus: 'VERIFIED',
    sourceType: 'AUTHORITATIVE_SOURCE',
    evidenceTier: 'PRIMARY_SOURCE',
    isVerbatimText: true,
    effectiveDate: '2026-01-01',
    validFrom: '2026-01-01',
    lastVerifiedDate: '2026-09-01',
    reviewAuditCycleDays: 365
  },

  CPF_ACCOUNT_ALLOCATION_RATES: {
    id: 'CPF_ACCOUNT_ALLOCATION_RATES',
    authority: 'CPF',
    authorityName: 'Central Provident Fund Board (CPF)',
    sourcePublisher: 'Singapore Statutes Online / AGC',
    legalOrStandardInstrument: 'Central Provident Fund Act 1953',
    actTitle: 'Central Provident Fund Act 1953',
    actCode: 'CPFA1953',
    sectionOrSchedule: 'Section 13 & First Schedule',
    ruleTitle: 'Statutory Allocation of Monthly CPF Contributions across OA, SA/RA, and MA by Age Bracket',
    category: 'CPF_PAYROLL',
    principle: 'Under Section 13 and the First Schedule of the Central Provident Fund Act 1953, the total monthly CPF contribution paid in respect of an employee is credited to the employee\'s Ordinary Account (OA), Special Account (SA / Retirement Account RA from age 55), and MediSave Account (MA) according to statutory allocation ratios determined by the employee\'s age band.',
    verbatimStatuteText: 'Every contribution paid into the Fund under section 7 in respect of an employee shall be credited to the prescribed accounts of that employee in such proportions as may be prescribed by regulations made under this Act according to the age of the employee.',
    application: 'Monthly payroll and accounting reconciliation: Allocating total 37% CPF (age <= 35) into OA (0.6217 of total CPF, ~23% of wages), SA (0.1621 of total CPF, ~6% of wages), and MA (0.2162 of total CPF, ~8% of wages).',
    practicalRules: [
      'Age <= 35: Total CPF 37% allocated as OA: 23%, SA: 6%, MA: 8%.',
      'Age > 35 to 45: Total CPF 37% allocated as OA: 21%, SA: 7%, MA: 9%.',
      'Age > 45 to 50: Total CPF 37% allocated as OA: 19%, SA: 8%, MA: 10%.',
      'Age > 50 to 55: Total CPF 37% allocated as OA: 15%, SA: 11.5%, MA: 10.5%.',
      'Age > 55 to 60: Total CPF 30% allocated as OA: 12%, SA/RA: 7.5%, MA: 10.5%.',
      'Age > 60 to 65: Total CPF 21% allocated as OA: 3.5%, SA/RA: 7%, MA: 10.5%.',
      'Age > 65 to 70: Total CPF 16.5% allocated as OA: 1%, SA/RA: 5%, MA: 10.5%.',
      'Age > 70: Total CPF 12.5% allocated as OA: 1%, SA/RA: 1%, MA: 10.5%.'
    ],
    canonicalUrl: 'https://sso.agc.gov.sg/Act/CPFA1953?ProvIds=P12-#pr13-',
    tags: ['cpf account allocation', 'ordinary account', 'special account', 'medisave account', 'oa sa ma ratio', 'section 13'],
    sourceStatus: 'VERIFIED',
    sourceType: 'AUTHORITATIVE_SOURCE',
    evidenceTier: 'PRIMARY_SOURCE',
    isVerbatimText: true,
    effectiveDate: '2026-01-01',
    validFrom: '2026-01-01',
    lastVerifiedDate: '2026-09-01',
    reviewAuditCycleDays: 365
  },

  CPF_WAGE_CEILING_2024: {
    id: 'CPF_WAGE_CEILING_2024',
    authority: 'CPF',
    authorityName: 'Central Provident Fund Board (CPF)',
    sourcePublisher: 'Singapore Statutes Online / AGC',
    legalOrStandardInstrument: 'Central Provident Fund Act 1953',
    actTitle: 'Central Provident Fund Act 1953',
    actCode: 'CPFA1953',
    sectionOrSchedule: 'First Schedule',
    ruleTitle: 'Historical Ordinary Wage (OW) Monthly Ceiling ($6,800 in 2024)',
    category: 'CPF_PAYROLL',
    principle: 'From 1 January 2024 to 31 December 2024, the statutory CPF Ordinary Wage monthly ceiling was SGD 6,800 under the second phase of the multi-year ceiling increases.',
    verbatimStatuteText: 'For the year 2024, the maximum monthly ordinary wage for which contributions are payable shall be $6,800.',
    application: 'Historical payroll audit and retroactive wage computations for calendar year 2024.',
    practicalRules: [
      'Monthly OW Ceiling: SGD 6,800.',
      'Max Employee CPF (20%): SGD 1,360.',
      'Max Employer CPF (17%): SGD 1,156 (Total: SGD 2,516).',
      'Superseded: Replaced by $7,400 on 1 January 2025.'
    ],
    canonicalUrl: 'https://sso.agc.gov.sg/Act/CPFA1953?ProvIds=P18-#Sc1-',
    tags: ['cpf ceiling', 'ordinary wage ceiling', 'wage ceiling', 'cpf ceiling 2024', '6800 ceiling', 'historical cpf 2024', 'ow ceiling 6800'],
    sourceStatus: 'HISTORICAL',
    sourceType: 'AUTHORITATIVE_SOURCE',
    evidenceTier: 'PRIMARY_SOURCE',
    isVerbatimText: true,
    effectiveDate: '2024-01-01',
    validFrom: '2024-01-01',
    validTo: '2024-12-31',
    lastVerifiedDate: '2026-09-01',
    reviewAuditCycleDays: 365,
    supersededByRecordId: 'CPF_WAGE_CEILING_2025'
  },

  CPF_WAGE_CEILING_2025: {
    id: 'CPF_WAGE_CEILING_2025',
    authority: 'CPF',
    authorityName: 'Central Provident Fund Board (CPF)',
    sourcePublisher: 'Singapore Statutes Online / AGC',
    legalOrStandardInstrument: 'Central Provident Fund Act 1953',
    actTitle: 'Central Provident Fund Act 1953',
    actCode: 'CPFA1953',
    sectionOrSchedule: 'First Schedule',
    ruleTitle: 'Historical Ordinary Wage (OW) Monthly Ceiling ($7,400 in 2025)',
    category: 'CPF_PAYROLL',
    principle: 'From 1 January 2025 to 31 December 2025, the statutory CPF Ordinary Wage monthly ceiling was SGD 7,400 under the third phase of the ceiling increases.',
    verbatimStatuteText: 'For the year 2025, the maximum monthly ordinary wage for which contributions are payable shall be $7,400.',
    application: 'Historical payroll audit and retroactive wage computations for calendar year 2025.',
    practicalRules: [
      'Monthly OW Ceiling: SGD 7,400.',
      'Max Employee CPF (20%): SGD 1,480.',
      'Max Employer CPF (17%): SGD 1,258 (Total: SGD 2,738).',
      'Superseded: Replaced by $8,000 on 1 January 2026.'
    ],
    canonicalUrl: 'https://sso.agc.gov.sg/Act/CPFA1953?ProvIds=P18-#Sc1-',
    tags: ['cpf ceiling', 'ordinary wage ceiling', 'wage ceiling', 'cpf ceiling 2025', '7400 ceiling', 'historical cpf 2025', 'ow ceiling 7400'],
    sourceStatus: 'HISTORICAL',
    sourceType: 'AUTHORITATIVE_SOURCE',
    evidenceTier: 'PRIMARY_SOURCE',
    isVerbatimText: true,
    effectiveDate: '2025-01-01',
    validFrom: '2025-01-01',
    validTo: '2025-12-31',
    lastVerifiedDate: '2026-09-01',
    reviewAuditCycleDays: 365,
    supersededByRecordId: 'CPF_WAGE_CEILINGS_2026',
    historicalPredecessorRecordId: 'CPF_WAGE_CEILING_2024'
  },

  // -------------------------------------------------------------

  // -------------------------------------------------------------
  CPF_RATES_BY_AGE_2026: {
    id: 'CPF_RATES_BY_AGE_2026',
    authority: 'CPF',
    authorityName: 'Central Provident Fund Board (CPF)',
    actTitle: 'Central Provident Fund Act 1953',
    actCode: 'CPFA1953',
    sectionOrSchedule: 'First Schedule (Statutory Contribution Rates)',
    ruleTitle: 'Tiered CPF Contribution Rates by Employee Age Bracket & 2026 Ceilings',
    category: 'CPF_PAYROLL',
    principle: 'Mandatory CPF contributions for Singapore Citizens and Permanent Residents (from 3rd year of PR status onwards) are calculated using tiered statutory percentage rates based on the employee\'s age.',
    application: 'Monthly payroll computation for all citizen and permanent resident employees.',
    practicalRules: [
      'Age 55 and below: Employer 17%, Employee 20% (Total: 37%).',
      'Age above 55 to 60: Employer 15%, Employee 15% (Total: 30% - ongoing senior worker rate enhancement).',
      'Age above 60 to 65: Employer 11.5%, Employee 9.5% (Total: 21%).',
      'Age above 65 to 70: Employer 9%, Employee 7.5% (Total: 16.5%).',
      'Age above 70: Employer 7.5%, Employee 5% (Total: 12.5%).',
      '2026 Ordinary Wage (OW) Monthly Ceiling: SGD 8,000 (effective 1 January 2026). Max monthly contribution for age $\\le 55$ is SGD 1,360 (employer) + SGD 1,600 (employee) = SGD 2,960.',
      'Additional Wage (AW) Ceiling: $$\\text{AW Ceiling} = \\text{SGD 102,000} - \\text{Total OW subject to CPF in the year}$$.'
    ],
    canonicalUrl: 'https://www.cpf.gov.sg/employer/employer-obligations/how-much-cpf-contributions-to-pay',
    tags: ['cpf rates by age', 'cpf contribution table', 'senior worker cpf', 'cpf 55 60', 'cpf rates 2026', 'cpf age brackets'],
    sourceStatus: 'NEEDS_REVIEW',
    sourceType: 'CURATED_SUMMARY',
    evidenceTier: 'CURATED_SUMMARY',
    isVerbatimText: false,
    effectiveDate: '2026-01-01'
  },

  // -------------------------------------------------------------
};
