import type { SingaporeStatuteRule } from './types';export const GST_STATUTE_RULES: Record<string, SingaporeStatuteRule> = {  // -------------------------------------------------------------
  GST_REMISSION_QUALIFYING_FUNDS: {
    id: 'GST_REMISSION_QUALIFYING_FUNDS', authority: 'IRAS', authorityName: 'Inland Revenue Authority of Singapore (IRAS)',
    sourcePublisher: 'Inland Revenue Authority of Singapore (IRAS)', legalOrStandardInstrument: 'IRAS GST guidance — Claiming GST on expenses for qualifying funds',
    actTitle: 'GST remission for qualifying funds', actCode: 'GSTA1993', sectionOrSchedule: 'IRAS Finance guidance',
    ruleTitle: 'GST Remission for Qualifying Funds (Including VCCs)', category: 'TAX_GST',
    principle: 'GST remission lets a qualifying fund, including a standalone VCC or sub-fund of an umbrella VCC, claim GST on qualifying fund expenses at an annual fixed recovery rate, subject to the remission conditions.',
    application: 'Use this for an investment fund or VCC considering whether it may recover GST incurred on fund expenses. It is not a general GST refund available to every business.',
    practicalRules: ['The fund must be managed by a prescribed fund manager in Singapore.', 'The fund must satisfy the conditions for its relevant income-tax concession as at the last day of its preceding financial year.', 'Claims remain subject to disallowed-expense restrictions under Regulations 26 and 27.', 'Each qualifying fund, including each VCC sub-fund, files a quarterly Statement of Claims due one month after the relevant quarter.', 'IRAS guidance states that the remission is granted until 31 December 2029; confirm eligibility and the applicable recovery rate before filing.'],
    canonicalUrl: 'https://www.iras.gov.sg/taxes/goods-services-tax-%28gst%29/specific-business-sectors/finance',
    supplementaryOfficialSources: [{ title: 'IRAS — Explanatory Notes to GST Remission for Prescribed Funds', url: 'https://www.iras.gov.sg/media/docs/default-source/uploadedfiles/pdf/explanatory-notes-to-gst-remission-for-prescribed-funds.pdf', authority: 'IRAS' }],
    tags: ['gst remission', 'gst remission for qualifying funds', 'gst remission for prescribed funds', 'qualifying funds', 'fixed recovery rate', 'statement of claims'],
    sourceStatus: 'VERIFIED', sourceType: 'CURATED_SUMMARY', evidenceTier: 'OFFICIAL_GUIDANCE', isVerbatimText: false,
    effectiveDate: '2026-09-14', validFrom: '2020-01-01', validTo: '2029-12-31', lastVerifiedDate: '2026-09-14', reviewAuditCycleDays: 90
  },

  GST_REGISTRATION_COMPULSORY_THRESHOLD: {
    id: 'GST_REGISTRATION_COMPULSORY_THRESHOLD',
    authority: 'IRAS',
    authorityName: 'Inland Revenue Authority of Singapore (IRAS)',
    actTitle: 'Goods and Services Tax Act 1993',
    actCode: 'GSTA1993',
    sectionOrSchedule: 'First Schedule',
    ruleTitle: 'Compulsory GST Registration Threshold ($1,000,000 Turnover)',
    category: 'TAX_GST',
    principle: 'A business is legally liable to register for GST if its taxable turnover exceeds SGD 1,000,000 under either the retrospective or prospective basis.',
    verbatimStatuteText: 'A person who makes taxable supplies but is not registered shall be liable to be registered— (a) at the end of any calendar year if the total value of taxable supplies made by him in that year has exceeded $1,000,000; or (b) at any time if there are reasonable grounds for believing that the total value of taxable supplies to be made by him in the period of 12 months then beginning will exceed $1,000,000.',
    application: 'SMEs must monitor taxable turnover at the end of each calendar year and projected 12 months.',
    practicalRules: [
      'Retrospective Basis: Taxable turnover at the end of the calendar year (31 Dec) exceeds SGD 1,000,000. Must apply for registration within 30 days (by 30 Jan).',
      'Prospective Basis: At any time, you reasonably expect taxable turnover in the next 12 months to exceed SGD 1,000,000. Must apply for registration within 30 days of the date of forecast.',
      'Voluntary Registration: Businesses below SGD 1M turnover may voluntarily register, but must remain registered for at least 2 years and maintain GIRO for payment/refunds.',
      'GST Rate: Standard rate is 9% (effective 1 January 2024).'
    ],
    canonicalUrl: 'https://sso.agc.gov.sg/Act/GSTA1993?ProvIds=P112-#Sc1-',
    tags: ['gst registration', 'turnover 1m', 'compulsory gst', 'prospective', 'retrospective'],
    sourceStatus: 'VERIFIED',
    sourceType: 'AUTHORITATIVE_SOURCE',
    evidenceTier: 'PRIMARY_SOURCE',
    isVerbatimText: true,
    effectiveDate: '2024-01-01'
  },

  GST_REG26_BLOCKED_INPUT_TAX: {
    id: 'GST_REG26_BLOCKED_INPUT_TAX',
    authority: 'IRAS',
    authorityName: 'Inland Revenue Authority of Singapore (IRAS)',
    actTitle: 'GST (General) Regulations',
    actCode: 'GSTA1993',
    sectionOrSchedule: 'Regulation 26 & 27',
    ruleTitle: 'Disallowed / Blocked Input Tax Claims under Singapore GST Law',
    category: 'TAX_GST',
    principle: 'Regulations 26 and 27 generally disallow input tax on specified expenses, subject to the scope limits and exceptions in the regulations and IRAS guidance. Business purpose alone does not make a blocked claim recoverable.',
    application: 'For motor-car costs, distinguish use by the taxable person or its employees from use by a third party or connected person, and check the vehicle definition and ordinary input-tax conditions. For staff medical costs, check the type and date of treatment and the statutory exception relied on.',
    practicalRules: [
      '1. Motor Cars (Regulation 27): Input tax on the purchase and running expenses of a motor car, and goods or services supplied directly in connection with it, is generally blocked; check the Regulation 25(1) definition and exclusions. For cars used by the taxable person or its employees, use includes both physical use and economic use to make supplies. From 1 January 2023, input tax on motor-car costs incurred for a third party may be claimed if the ordinary input-tax conditions are met. Costs for a connected person remain blocked unless the taxable person recovers the costs (only the recovered portion where recovery is partial) and that recovery is not ancillary to another supply to that connected person.',
      '2. Club Subscription Fees (Regulation 26): Joining, membership, subscription and transfer fees charged by sports and recreation clubs are disallowed; expenses for using club facilities may be claimable if the ordinary conditions are met.',
      '3. Staff Medical and Insurance (Regulation 26): Staff medical expenses are disallowed unless obligatory under WICA or a collective agreement, or, for expenses incurred on or after 1 October 2021, the medical treatment is connected to a health risk or requirement arising from the nature of the work or work environment and is either required under Singapore written law or related to COVID-19 and provided under a Government or public-authority advisory. IRAS also allows qualifying pre-employment medical examinations used to assess a candidate’s suitability, subject to ordinary claim conditions. Staff medical or accident insurance premiums have the narrower WICA or collective-agreement exception.',
      '4. Family Benefits (Regulation 26): Benefits provided to employees’ family members or relatives are disallowed.',
      '5. Betting and Games of Chance (Regulation 26): Transactions involving betting, sweepstakes, lotteries, fruit machines or games of chance are disallowed.'
    ],
    canonicalUrl: 'https://www.iras.gov.sg/taxes/goods-services-tax-(gst)/claiming-gst-(input-tax)/conditions-for-claiming-input-tax',
    supplementaryOfficialSources: [{
      title: 'IRAS — Purchase and Sale of Motor Vehicles',
      url: 'https://www.iras.gov.sg/taxes/goods-services-tax-%28gst%29/claiming-gst-%28input-tax%29/common-scenarios---do-i-claim-gst/purchase-and-sale-of-motor-vehicles',
      authority: 'IRAS'
    }],
    tags: ['blocked input tax', 'regulation 26', 'regulation 27', 'gst car claim', 'medical insurance gst', 'club subscriptions'],
    sourcePublisher: 'Inland Revenue Authority of Singapore (IRAS)',
    sourceType: 'CURATED_SUMMARY',
    evidenceTier: 'OFFICIAL_GUIDANCE',
    isVerbatimText: false,
    sourceStatus: 'VERIFIED',
    lastVerifiedDate: '2026-09-26',
    reviewAuditCycleDays: 90
  },

  GST_SEC21_ZERO_RATED_EXPORTS: {
    id: 'GST_SEC21_ZERO_RATED_EXPORTS',
    authority: 'IRAS',
    authorityName: 'Inland Revenue Authority of Singapore (IRAS)',
    actTitle: 'Goods and Services Tax Act 1993',
    actCode: 'GSTA1993',
    sectionOrSchedule: 'Section 21(3)',
    ruleTitle: 'Zero-Rating of International Services and Exported Goods (0% GST)',
    category: 'TAX_GST',
    principle: 'A supply of exported goods or services is zero-rated only where it satisfies the requirements of the relevant zero-rating provision. A service must fall within a specific category in Section 21(3) and meet that category’s conditions; an overseas customer alone is insufficient.',
    application: 'Identify the service category and applicable Section 21(3) limb. Check the contract, direct beneficiary and belonging status where required, the place of performance where relevant to that limb, and any connection to land or goods in Singapore. Separately assess input-tax recovery under the ordinary attribution, documentation and blocked-input rules.',
    practicalRules: [
      'Goods Export: Must maintain required export documentation (Bill of Lading, Air Waybill, export permits) within 60 days.',
      'International Services (Section 21(3)): Not all services supplied to overseas customers qualify. Apply the conditions of the specific paragraph; for example, Section 21(3)(j) includes a contract and direct-benefit test and, for an overseas person, requires that person to be outside Singapore when the service is performed. Other paragraphs have their own service, recipient, place or goods-related conditions.',
      'Input Tax: A zero-rated taxable supply may support recovery of attributable input tax, but recovery remains subject to the normal input-tax conditions, attribution and partial-exemption rules, and Regulations 26 and 27.'
    ],
    canonicalUrl: 'https://sso.agc.gov.sg/Act/GSTA1993?ProvIds=P15-#pr21-',
    supplementaryOfficialSources: [{ title: 'IRAS — Providing International Services', url: 'https://www.iras.gov.sg/taxes/goods-services-tax-%28gst%29/charging-gst-%28output-tax%29/when-to-charge-0-gst-%28zero-rate%29/providing-international-services', authority: 'IRAS' }],
    tags: ['zero rated', '0% gst', 'export of services', 'section 21(3)', 'international services']
  },

  GST_REG28_DE_MINIMIS_RULE: {
    id: 'GST_REG28_DE_MINIMIS_RULE',
    authority: 'IRAS',
    authorityName: 'Inland Revenue Authority of Singapore (IRAS)',
    sourcePublisher: 'Singapore Statutes Online / AGC',
    legalOrStandardInstrument: 'GST (General) Regulations',
    actTitle: 'GST (General) Regulations',
    actCode: 'GSTA1993',
    sectionOrSchedule: 'Regulation 28',
    ruleTitle: 'De Minimis Rule for Input Tax Attribution on Exempt Supplies (Partial Exemption)',
    category: 'TAX_GST',
    principle: 'Under Regulation 28 of the GST (General) Regulations, a taxable person making exempt supplies is treated as having incurred input tax exclusively attributable to taxable supplies and may claim full input tax if the value of exempt supplies does not exceed an average of SGD 40,000 per month AND 5% of the total value of all supplies made in that prescribed accounting period.',
    verbatimStatuteText: 'Where in any prescribed accounting period the value of exempt supplies made by a taxable person does not exceed an average of $40,000 per month and 5% of the total value of all supplies made by him in that period, all input tax incurred by him in that period shall be treated as attributable to taxable supplies.',
    application: 'Businesses earning incidental exempt income (e.g. fixed deposit interest, realised foreign exchange gains): 100% of input tax on general business overheads remains recoverable under the De Minimis test.',
    practicalRules: [
      'Dual Quantitative Thresholds: Value of exempt supplies must be <= SGD 40,000 per month on average AND <= 5% of total value of all supplies in that accounting period.',
      'Benefit of Passing Test: Entitled to recover in full all input tax incurred, without requiring complex input tax apportionment calculations.',
      'Failure of Test: If either threshold is breached, the entity is in partial exemption and must apportion input tax using the standard turnover formula.',
      'Annual Review: An annual longer-period input tax adjustment is mandatory at the end of each tax year.'
    ],
    canonicalUrl: 'https://sso.agc.gov.sg/SL/GSTA1993-RG1?ProvIds=P15-#pr28-',
    tags: ['de minimis rule', 'regulation 28', 'partial exemption', 'exempt supplies 40000', 'input tax recovery 5%'],
    sourceStatus: 'VERIFIED',
    sourceType: 'AUTHORITATIVE_SOURCE',
    evidenceTier: 'PRIMARY_SOURCE',
    isVerbatimText: true,
    effectiveDate: '1994-04-01',
    validFrom: '1994-04-01',
    lastVerifiedDate: '2026-09-01',
    reviewAuditCycleDays: 365
  },

  GST_SEC14_REVERSE_CHARGE: {
    id: 'GST_SEC14_REVERSE_CHARGE',
    authority: 'IRAS',
    authorityName: 'Inland Revenue Authority of Singapore (IRAS)',
    sourcePublisher: 'Singapore Statutes Online / AGC',
    legalOrStandardInstrument: 'Goods and Services Tax Act 1993',
    actTitle: 'Goods and Services Tax Act 1993',
    actCode: 'GSTA1993',
    sectionOrSchedule: 'Section 14 & Seventh Schedule',
    ruleTitle: 'Reverse Charge on Business-to-Business (B2B) Imported Services & Distantly Taxable Goods',
    category: 'TAX_GST',
    principle: 'Under Section 14 and the Seventh Schedule of the Goods and Services Tax Act 1993, a GST-registered person who is not entitled to full input tax recovery (or who belongs to a reverse charge group) must account for output tax under the Reverse Charge mechanism on all imported services and imported distantly taxable goods procured from overseas suppliers.',
    verbatimStatuteText: 'Where a person who is registered or liable to be registered receives imported services or imported distantly taxable goods from a supplier who belongs in a country other than Singapore, the recipient shall account for and pay tax on the supply of those services or goods as if the recipient had himself supplied them in Singapore in the course or furtherance of his business.',
    application: 'Financial institutions, investment holding companies, and residential property developers procuring overseas software, cloud servers, or consultancy must account for 9% Reverse Charge output tax in Box 1 of GST F5.',
    practicalRules: [
      'Applicability: Mandatory for GST-registered persons not entitled to full input tax recovery (e.g. banks, insurers, exempt supply businesses).',
      'Fully Taxable Businesses: Fully taxable businesses entitled to 100% input tax recovery are generally not required to apply reverse charge unless electing under group relief.',
      'Tax Mechanism: Account for 9% output tax in Box 1; claim allowable input tax in Box 7 in the same GST return.',
      'Distantly Taxable Goods (LVG): Goods located outside Singapore with a value at or below the SGD 400 import threshold delivered to Singapore.'
    ],
    canonicalUrl: 'https://sso.agc.gov.sg/Act/GSTA1993?ProvIds=P13-#pr14-',
    tags: ['reverse charge', 'section 14', 'imported services', 'seventh schedule', 'b2b imported services'],
    sourceStatus: 'VERIFIED',
    sourceType: 'AUTHORITATIVE_SOURCE',
    evidenceTier: 'PRIMARY_SOURCE',
    isVerbatimText: true,
    effectiveDate: '2020-01-01',
    validFrom: '2020-01-01',
    lastVerifiedDate: '2026-09-01',
    reviewAuditCycleDays: 365
  },

  GST_REG82_90_BAD_DEBT_RELIEF: {
    id: 'GST_REG82_90_BAD_DEBT_RELIEF',
    authority: 'IRAS',
    authorityName: 'Inland Revenue Authority of Singapore (IRAS)',
    sourcePublisher: 'Singapore Statutes Online / AGC',
    legalOrStandardInstrument: 'GST (General) Regulations',
    actTitle: 'GST (General) Regulations',
    actCode: 'GSTA1993',
    sectionOrSchedule: 'Regulations 82–90',
    ruleTitle: 'GST Bad Debt Relief Scheme & Recovery of Output Tax on Defaulted Debts',
    category: 'TAX_GST',
    principle: 'Under Regulations 82 to 90 (Part X) of the GST (General) Regulations, a taxable person who has accounted for and paid output tax on a supply may make a claim for bad debt relief if the debt has remained unpaid for at least 12 months from the date of supply (or the debtor has become insolvent) and reasonable steps have been taken to pursue payment, with the debt formally written off in accounts.',
    verbatimStatuteText: 'A taxable person shall be entitled to make a claim for bad debt relief under these Regulations if the whole or part of the consideration for the supply has been written off in his accounts as a bad debt and a period of 12 months beginning with the date of the supply has elapsed, or the debtor has become insolvent before the expiration of that period.',
    application: 'When an outstanding trade receivable of SGD 10,900 (inclusive of SGD 900 GST) is unpaid after 12 months, the company writes off the debt and claims SGD 900 back in Box 7 of GST F5 as Bad Debt Relief.',
    practicalRules: [
      '12-Month Rule: At least 12 months must have elapsed from the date of the supply, or the customer is proven formally insolvent.',
      'Written Off in Accounts: The debt must be formally written off as bad in the general ledger and financial statements.',
      'Reasonable Recovery Efforts: Entity must have made commercial recovery efforts (reminders, legal demand letters).',
      'Subsequent Recovery: If debtor subsequently pays all or part of the bad debt, output tax must be repaid to IRAS in Box 1 in that subsequent period.'
    ],
    canonicalUrl: 'https://sso.agc.gov.sg/SL/GSTA1993-RG1?ProvIds=P112-#pr82-',
    tags: ['bad debt relief', 'regulations 82 90', 'output tax refund', '12 months bad debt', 'bad debt write off'],
    sourceStatus: 'VERIFIED',
    sourceType: 'AUTHORITATIVE_SOURCE',
    evidenceTier: 'PRIMARY_SOURCE',
    isVerbatimText: true,
    effectiveDate: '1994-04-01',
    validFrom: '1994-04-01',
    lastVerifiedDate: '2026-09-01',
    reviewAuditCycleDays: 365
  },

  GST_SEC11_TIME_OF_SUPPLY: {
    id: 'GST_SEC11_TIME_OF_SUPPLY',
    authority: 'IRAS',
    authorityName: 'Inland Revenue Authority of Singapore (IRAS)',
    sourcePublisher: 'Singapore Statutes Online / AGC',
    legalOrStandardInstrument: 'Goods and Services Tax Act 1993',
    actTitle: 'Goods and Services Tax Act 1993',
    actCode: 'GSTA1993',
    sectionOrSchedule: 'Section 11',
    ruleTitle: 'General Time of Supply Rules (Invoice Issuance or Payment Receipt)',
    category: 'TAX_GST',
    principle: 'For most transactions, the time of supply is the earlier of when an invoice is issued and when payment is received. Delivery of goods or performance of services is not an additional general trigger under the current rule; specific statutory rules can apply to particular supplies.',
    verbatimStatuteText: 'Subject to the provisions of this Act, a supply of goods or services shall be treated as taking place — (a) at the time when an invoice in respect of the supply is issued; or (b) at the time when any payment in respect of the supply is received by the supplier, whichever is the earlier.',
    application: 'Determine the GST reporting period using the invoice date and payment-received date, and check whether a specific time-of-supply rule applies. Do not use delivery, service completion or the historical 14-day rule as an extra current general trigger.',
    practicalRules: [
      'Current General Rule: For most transactions, use the earlier of invoice issuance and receipt of payment. A document triggers the rule when it functions as a bill for payment; a pro-forma invoice or statement of account may not do so.',
      'Historical Transition: The pre-1 January 2011 general regime used a Basic Tax Point and a 14-day rule. Do not apply those historical rules to supplies on or after 1 January 2011; check the applicable historical law for an earlier supply.',
      'Continuous Supplies of Services: Time of supply is the earlier of invoice issuance or payment receipt.',
      'Deposit / Prepayments: GST must be accounted for on deposits or prepayments in the period the cash is received.'
    ],
    canonicalUrl: 'https://sso.agc.gov.sg/Act/GSTA1993?ProvIds=P13-#pr11-',
    supplementaryOfficialSources: [
      { title: 'IRAS — When to Report Supplies in GST Returns', url: 'https://www.iras.gov.sg/taxes/goods-services-tax-%28gst%29/charging-gst-%28output-tax%29/when-to-report-supplies-in-gst-returns', authority: 'IRAS' },
      { title: 'IRAS — GST: Time of Supply Rules (Historical Transition)', url: 'https://www.iras.gov.sg/media/docs/default-source/uploadedfiles/pdf/gst-tos-rules.pdf?sfvrsn=14973190_0', authority: 'IRAS' }
    ],
    tags: ['time of supply', 'section 11', 'tax point', 'invoice date', 'payment date', 'earliest date'],
    sourceStatus: 'VERIFIED',
    sourceType: 'AUTHORITATIVE_SOURCE',
    evidenceTier: 'PRIMARY_SOURCE',
    isVerbatimText: true,
    effectiveDate: '2011-01-01',
    validFrom: '2011-01-01',
    lastVerifiedDate: '2026-09-26',
    reviewAuditCycleDays: 365
  },

  GST_RATE_7_PERCENT: {
    id: 'GST_RATE_7_PERCENT',
    authority: 'IRAS',
    authorityName: 'Inland Revenue Authority of Singapore (IRAS)',
    sourcePublisher: 'Singapore Statutes Online / AGC',
    legalOrStandardInstrument: 'Goods and Services Tax Act 1993',
    actTitle: 'Goods and Services Tax Act 1993',
    actCode: 'GSTA1993',
    sectionOrSchedule: 'Section 16',
    ruleTitle: 'Historical Singapore GST Rate (7% Prior to 1 January 2023)',
    category: 'TAX_GST',
    principle: 'Section 16 specifies a 7% standard rate from 1 July 2007 to 31 December 2022. The applicable rate for a cross-boundary supply also depends on time-of-supply and transitional provisions.',
    verbatimStatuteText: '7% for the period from 1 July 2007 to 31 December 2022 (both dates inclusive)',
    application: 'Historical audit and accounting checks for supplies within this statutory period, subject to applicable transition rules.',
    practicalRules: [
      'Rate: 7% on standard-rated supplies.',
      'Validity Period: In force until 31 December 2022.',
      'Superseded: Replaced by 8% GST on 1 January 2023 under Section 16 statutory amendment.'
    ],
    canonicalUrl: 'https://sso.agc.gov.sg/Act/GSTA1993?ProvIds=pr16-',
    tags: ['7% gst', 'gst rate', 'tax rate', 'rate of tax', 'historical gst', 'gst rate 7', 'gst prior to 2023', 'standard rate'],
    sourceStatus: 'HISTORICAL',
    sourceType: 'AUTHORITATIVE_SOURCE',
    evidenceTier: 'PRIMARY_SOURCE',
    isVerbatimText: true,
    effectiveDate: '2007-07-01',
    validFrom: '2007-07-01',
    validTo: '2022-12-31',
    lastVerifiedDate: '2026-09-26',
    reviewAuditCycleDays: 365,
    supersededByRecordId: 'GST_RATE_8_PERCENT_2023'
  },

  GST_RATE_8_PERCENT_2023: {
    id: 'GST_RATE_8_PERCENT_2023',
    authority: 'IRAS',
    authorityName: 'Inland Revenue Authority of Singapore (IRAS)',
    sourcePublisher: 'Singapore Statutes Online / AGC',
    legalOrStandardInstrument: 'Goods and Services Tax Act 1993',
    actTitle: 'Goods and Services Tax Act 1993',
    actCode: 'GSTA1993',
    sectionOrSchedule: 'Section 16',
    ruleTitle: 'Historical Singapore GST Rate (8% in Calendar Year 2023)',
    category: 'TAX_GST',
    principle: 'Section 16 specifies an 8% standard rate from 1 January to 31 December 2023. The applicable rate for a cross-boundary supply also depends on time-of-supply and transitional provisions.',
    verbatimStatuteText: '8% for the period from 1 January 2023 to 31 December 2023 (both dates inclusive)',
    application: 'Historical transactions and audit verification for supplies within this statutory period, subject to applicable transition rules.',
    practicalRules: [
      'Rate: 8% on all standard-rated supplies made between 1 January 2023 and 31 December 2023.',
      'Transitional Rules: Do not determine the rate from the calendar date alone for supplies spanning 2023/2024. Check invoice, payment and delivery/performance timing and the applicable IRAS transitional rule or election.',
      'Superseded: Replaced by 9% GST on 1 January 2024.'
    ],
    canonicalUrl: 'https://sso.agc.gov.sg/Act/GSTA1993?ProvIds=pr16-',
    tags: ['8% gst', 'gst rate', 'tax rate', 'rate of tax', '2023 gst', 'historical 8%', 'gst rate 8% 2023', 'standard rate'],
    sourceStatus: 'HISTORICAL',
    sourceType: 'AUTHORITATIVE_SOURCE',
    evidenceTier: 'PRIMARY_SOURCE',
    isVerbatimText: true,
    effectiveDate: '2023-01-01',
    validFrom: '2023-01-01',
    validTo: '2023-12-31',
    lastVerifiedDate: '2026-09-26',
    reviewAuditCycleDays: 365,
    supersededByRecordId: 'GST_RATE_9_PERCENT',
    historicalPredecessorRecordId: 'GST_RATE_7_PERCENT'
  },

  GST_RATE_9_PERCENT: {
    id: 'GST_RATE_9_PERCENT',
    authority: 'IRAS',
    authorityName: 'Inland Revenue Authority of Singapore (IRAS)',
    sourcePublisher: 'Singapore Statutes Online / AGC',
    legalOrStandardInstrument: 'Goods and Services Tax Act 1993',
    actTitle: 'Goods and Services Tax Act 1993',
    actCode: 'GSTA1993',
    sectionOrSchedule: 'Section 16',
    ruleTitle: 'Current Singapore Standard GST Rate (9% from 1 January 2024 Onwards)',
    category: 'TAX_GST',
    principle: 'Section 16 specifies a 9% standard rate from 1 January 2024. The applicable rate for a cross-boundary supply also depends on time-of-supply and transitional provisions.',
    verbatimStatuteText: '9% from and including 1 January 2024',
    application: 'Current standard-rated supplies and accounting checks, subject to applicable transition and time-of-supply rules.',
    practicalRules: [
      'Rate: 9% standard rate effective 1 January 2024 indefinitely.',
      'Input GST Claim: Claimable on qualifying business purchases under Section 19.',
      'Output GST: Collected on domestic taxable supplies and remitted to IRAS via quarterly Form F5.'
    ],
    canonicalUrl: 'https://sso.agc.gov.sg/Act/GSTA1993?ProvIds=pr16-',
    tags: ['9% gst', 'gst rate', 'tax rate', 'rate of tax', 'current gst rate', 'gst 9 percent', 'standard rate gst', 'standard rate'],
    sourceStatus: 'VERIFIED',
    sourceType: 'AUTHORITATIVE_SOURCE',
    evidenceTier: 'PRIMARY_SOURCE',
    isVerbatimText: true,
    effectiveDate: '2024-01-01',
    validFrom: '2024-01-01',
    lastVerifiedDate: '2026-09-26',
    reviewAuditCycleDays: 365,
    historicalPredecessorRecordId: 'GST_RATE_8_PERCENT_2023'
  },

  // -------------------------------------------------------------
};
