import type { SingaporeStatuteRule } from './types';export const GST_STATUTE_RULES: Record<string, SingaporeStatuteRule> = {  // -------------------------------------------------------------
  GST_REGISTRATION_COMPULSORY_THRESHOLD: {
    id: 'GST_REGISTRATION_COMPULSORY_THRESHOLD',
    authority: 'IRAS',
    authorityName: 'Inland Revenue Authority of Singapore (IRAS)',
    actTitle: 'Goods and Services Tax Act 1993',
    actCode: 'GSTA1993',
    sectionOrSchedule: 'First Schedule',
    ruleTitle: 'Compulsory GST Registration Threshold ($1,000,000 Turnover)',
    category: 'TAX_GST',
    principle: 'A business is legally liable to register for GST if its taxable turnover exceeds SGD 1,000,000 under either the retrospective or prospective basis.',
    verbatimStatuteText: 'A person who makes taxable supplies but is not registered shall be liable to be registered— (a) at the end of any calendar year if the total value of taxable supplies made by him in that year has exceeded $1,000,000; or (b) at any time if there are reasonable grounds for believing that the total value of taxable supplies to be made by him in the period of 12 months then beginning will exceed $1,000,000.',
    application: 'SMEs must monitor taxable turnover at the end of each calendar year and projected 12 months.',
    practicalRules: [
      'Retrospective Basis: Taxable turnover at the end of the calendar year (31 Dec) exceeds SGD 1,000,000. Must apply for registration within 30 days (by 30 Jan).',
      'Prospective Basis: At any time, you reasonably expect taxable turnover in the next 12 months to exceed SGD 1,000,000. Must apply for registration within 30 days of the date of forecast.',
      'Voluntary Registration: Businesses below SGD 1M turnover may voluntarily register, but must remain registered for at least 2 years and maintain GIRO for payment/refunds.',
      'GST Rate: Standard rate is 9% (effective 1 January 2024).'
    ],
    canonicalUrl: 'https://sso.agc.gov.sg/Act/GSTA1993?ProvIds=P112-#Sc1-',
    tags: ['gst registration', 'turnover 1m', 'compulsory gst', 'prospective', 'retrospective'],
    sourceStatus: 'VERIFIED',
    sourceType: 'AUTHORITATIVE_SOURCE',
    evidenceTier: 'PRIMARY_SOURCE',
    isVerbatimText: true,
    effectiveDate: '2024-01-01'
  },

  GST_REG26_BLOCKED_INPUT_TAX: {
    id: 'GST_REG26_BLOCKED_INPUT_TAX',
    authority: 'IRAS',
    authorityName: 'Inland Revenue Authority of Singapore (IRAS)',
    actTitle: 'GST (General) Regulations',
    actCode: 'GSTA1993',
    sectionOrSchedule: 'Regulation 26 & 27',
    ruleTitle: 'Disallowed / Blocked Input Tax Claims under Singapore GST Law',
    category: 'TAX_GST',
    principle: 'Input tax incurred on certain specified business goods or services is strictly disallowed from recovery, even if incurred for business purposes.',
    application: 'A GST-registered company cannot claim back the 9% input GST paid on company cars, club fees, or employee family medical coverage.',
    practicalRules: [
      '1. Motor Cars: Input tax incurred on the purchase, hire, or running expenses (petrol, parking, repair) of a passenger motor car (S-plate) is strictly non-claimable.',
      '2. Club Subscription Fees: Entrance fees and subscription charges paid to sports, recreational, or social clubs.',
      '3. Medical and Accident Insurance: Medical expenses and insurance premiums for staff (unless mandatory under Work Injury Compensation Act [WICA] or collective agreement). Medical expenses for staff family members are 100% blocked.',
      '4. Family Benefits: Any expenses incurred on benefits provided to the family members of your employees.',
      '5. Betting & Lotteries: Transactions involving games of chance, lotteries, and betting.'
    ],
    canonicalUrl: 'https://www.iras.gov.sg/taxes/goods-services-tax-(gst)/claiming-gst-(input-tax)/conditions-for-claiming-input-tax',
    tags: ['blocked input tax', 'regulation 26', 'gst car claim', 'medical insurance gst', 'club subscriptions']
  },

  GST_SEC21_ZERO_RATED_EXPORTS: {
    id: 'GST_SEC21_ZERO_RATED_EXPORTS',
    authority: 'IRAS',
    authorityName: 'Inland Revenue Authority of Singapore (IRAS)',
    actTitle: 'Goods and Services Tax Act 1993',
    actCode: 'GSTA1993',
    sectionOrSchedule: 'Section 21(3)',
    ruleTitle: 'Zero-Rating of International Services and Exported Goods (0% GST)',
    category: 'TAX_GST',
    principle: 'Supplies of goods exported out of Singapore and supplies of international services falling within Section 21(3) are zero-rated (taxed at 0%).',
    application: 'Singapore software companies exporting SaaS or advisory services to overseas clients bill at 0% GST and can still reclaim 9% input GST on business overheads.',
    practicalRules: [
      'Goods Export: Must maintain required export documentation (Bill of Lading, Air Waybill, export permits) within 60 days.',
      'International Services (Section 21(3)): Software, consulting, and management services provided under contract to overseas clients, directly benefiting an overseas person outside Singapore, qualify for 0% GST.',
      'Input Tax Benefit: Even though output tax is 0%, the business can claim 100% of input GST paid on qualifying business purchases.'
    ],
    canonicalUrl: 'https://sso.agc.gov.sg/Act/GSTA1993?ProvIds=P15-#pr21-',
    tags: ['zero rated', '0% gst', 'export of services', 'section 21(3)', 'international services']
  },

  GST_REG28_DE_MINIMIS_RULE: {
    id: 'GST_REG28_DE_MINIMIS_RULE',
    authority: 'IRAS',
    authorityName: 'Inland Revenue Authority of Singapore (IRAS)',
    sourcePublisher: 'Singapore Statutes Online / AGC',
    legalOrStandardInstrument: 'GST (General) Regulations',
    actTitle: 'GST (General) Regulations',
    actCode: 'GSTA1993',
    sectionOrSchedule: 'Regulation 28',
    ruleTitle: 'De Minimis Rule for Input Tax Attribution on Exempt Supplies (Partial Exemption)',
    category: 'TAX_GST',
    principle: 'Under Regulation 28 of the GST (General) Regulations, a taxable person making exempt supplies is treated as having incurred input tax exclusively attributable to taxable supplies and may claim full input tax if the value of exempt supplies does not exceed an average of SGD 40,000 per month AND 5% of the total value of all supplies made in that prescribed accounting period.',
    verbatimStatuteText: 'Where in any prescribed accounting period the value of exempt supplies made by a taxable person does not exceed an average of $40,000 per month and 5% of the total value of all supplies made by him in that period, all input tax incurred by him in that period shall be treated as attributable to taxable supplies.',
    application: 'Businesses earning incidental exempt income (e.g. fixed deposit interest, realised foreign exchange gains): 100% of input tax on general business overheads remains recoverable under the De Minimis test.',
    practicalRules: [
      'Dual Quantitative Thresholds: Value of exempt supplies must be <= SGD 40,000 per month on average AND <= 5% of total value of all supplies in that accounting period.',
      'Benefit of Passing Test: Entitled to recover in full all input tax incurred, without requiring complex input tax apportionment calculations.',
      'Failure of Test: If either threshold is breached, the entity is in partial exemption and must apportion input tax using the standard turnover formula.',
      'Annual Review: An annual longer-period input tax adjustment is mandatory at the end of each tax year.'
    ],
    canonicalUrl: 'https://sso.agc.gov.sg/SL/GSTA1993-RG1?ProvIds=P15-#pr28-',
    tags: ['de minimis rule', 'regulation 28', 'partial exemption', 'exempt supplies 40000', 'input tax recovery 5%'],
    sourceStatus: 'VERIFIED',
    sourceType: 'AUTHORITATIVE_SOURCE',
    evidenceTier: 'PRIMARY_SOURCE',
    isVerbatimText: true,
    effectiveDate: '1994-04-01',
    validFrom: '1994-04-01',
    lastVerifiedDate: '2026-09-01',
    reviewAuditCycleDays: 365
  },

  GST_SEC14_REVERSE_CHARGE: {
    id: 'GST_SEC14_REVERSE_CHARGE',
    authority: 'IRAS',
    authorityName: 'Inland Revenue Authority of Singapore (IRAS)',
    sourcePublisher: 'Singapore Statutes Online / AGC',
    legalOrStandardInstrument: 'Goods and Services Tax Act 1993',
    actTitle: 'Goods and Services Tax Act 1993',
    actCode: 'GSTA1993',
    sectionOrSchedule: 'Section 14 & Seventh Schedule',
    ruleTitle: 'Reverse Charge on Business-to-Business (B2B) Imported Services & Distantly Taxable Goods',
    category: 'TAX_GST',
    principle: 'Under Section 14 and the Seventh Schedule of the Goods and Services Tax Act 1993, a GST-registered person who is not entitled to full input tax recovery (or who belongs to a reverse charge group) must account for output tax under the Reverse Charge mechanism on all imported services and imported distantly taxable goods procured from overseas suppliers.',
    verbatimStatuteText: 'Where a person who is registered or liable to be registered receives imported services or imported distantly taxable goods from a supplier who belongs in a country other than Singapore, the recipient shall account for and pay tax on the supply of those services or goods as if the recipient had himself supplied them in Singapore in the course or furtherance of his business.',
    application: 'Financial institutions, investment holding companies, and residential property developers procuring overseas software, cloud servers, or consultancy must account for 9% Reverse Charge output tax in Box 1 of GST F5.',
    practicalRules: [
      'Applicability: Mandatory for GST-registered persons not entitled to full input tax recovery (e.g. banks, insurers, exempt supply businesses).',
      'Fully Taxable Businesses: Fully taxable businesses entitled to 100% input tax recovery are generally not required to apply reverse charge unless electing under group relief.',
      'Tax Mechanism: Account for 9% output tax in Box 1; claim allowable input tax in Box 7 in the same GST return.',
      'Distantly Taxable Goods (LVG): Goods located outside Singapore with a value at or below the SGD 400 import threshold delivered to Singapore.'
    ],
    canonicalUrl: 'https://sso.agc.gov.sg/Act/GSTA1993?ProvIds=P13-#pr14-',
    tags: ['reverse charge', 'section 14', 'imported services', 'seventh schedule', 'b2b imported services'],
    sourceStatus: 'VERIFIED',
    sourceType: 'AUTHORITATIVE_SOURCE',
    evidenceTier: 'PRIMARY_SOURCE',
    isVerbatimText: true,
    effectiveDate: '2020-01-01',
    validFrom: '2020-01-01',
    lastVerifiedDate: '2026-09-01',
    reviewAuditCycleDays: 365
  },

  GST_REG82_90_BAD_DEBT_RELIEF: {
    id: 'GST_REG82_90_BAD_DEBT_RELIEF',
    authority: 'IRAS',
    authorityName: 'Inland Revenue Authority of Singapore (IRAS)',
    sourcePublisher: 'Singapore Statutes Online / AGC',
    legalOrStandardInstrument: 'GST (General) Regulations',
    actTitle: 'GST (General) Regulations',
    actCode: 'GSTA1993',
    sectionOrSchedule: 'Regulations 82–90',
    ruleTitle: 'GST Bad Debt Relief Scheme & Recovery of Output Tax on Defaulted Debts',
    category: 'TAX_GST',
    principle: 'Under Regulations 82 to 90 (Part X) of the GST (General) Regulations, a taxable person who has accounted for and paid output tax on a supply may make a claim for bad debt relief if the debt has remained unpaid for at least 12 months from the date of supply (or the debtor has become insolvent) and reasonable steps have been taken to pursue payment, with the debt formally written off in accounts.',
    verbatimStatuteText: 'A taxable person shall be entitled to make a claim for bad debt relief under these Regulations if the whole or part of the consideration for the supply has been written off in his accounts as a bad debt and a period of 12 months beginning with the date of the supply has elapsed, or the debtor has become insolvent before the expiration of that period.',
    application: 'When an outstanding trade receivable of SGD 10,900 (inclusive of SGD 900 GST) is unpaid after 12 months, the company writes off the debt and claims SGD 900 back in Box 7 of GST F5 as Bad Debt Relief.',
    practicalRules: [
      '12-Month Rule: At least 12 months must have elapsed from the date of the supply, or the customer is proven formally insolvent.',
      'Written Off in Accounts: The debt must be formally written off as bad in the general ledger and financial statements.',
      'Reasonable Recovery Efforts: Entity must have made commercial recovery efforts (reminders, legal demand letters).',
      'Subsequent Recovery: If debtor subsequently pays all or part of the bad debt, output tax must be repaid to IRAS in Box 1 in that subsequent period.'
    ],
    canonicalUrl: 'https://sso.agc.gov.sg/SL/GSTA1993-RG1?ProvIds=P112-#pr82-',
    tags: ['bad debt relief', 'regulations 82 90', 'output tax refund', '12 months bad debt', 'bad debt write off'],
    sourceStatus: 'VERIFIED',
    sourceType: 'AUTHORITATIVE_SOURCE',
    evidenceTier: 'PRIMARY_SOURCE',
    isVerbatimText: true,
    effectiveDate: '1994-04-01',
    validFrom: '1994-04-01',
    lastVerifiedDate: '2026-09-01',
    reviewAuditCycleDays: 365
  },

  GST_SEC11_TIME_OF_SUPPLY: {
    id: 'GST_SEC11_TIME_OF_SUPPLY',
    authority: 'IRAS',
    authorityName: 'Inland Revenue Authority of Singapore (IRAS)',
    sourcePublisher: 'Singapore Statutes Online / AGC',
    legalOrStandardInstrument: 'Goods and Services Tax Act 1993',
    actTitle: 'Goods and Services Tax Act 1993',
    actCode: 'GSTA1993',
    sectionOrSchedule: 'Section 11',
    ruleTitle: 'General Time of Supply Rules (Invoice Issuance, Payment Receipt, Performance)',
    category: 'TAX_GST',
    principle: 'Under Section 11(1) of the Goods and Services Tax Act 1993, a supply of goods or services is treated as taking place at the earliest of: (a) the date a tax invoice is issued, (b) the date any payment in respect of the supply is received, or (c) the basic tax point when the goods are removed/made available or services performed.',
    verbatimStatuteText: 'Subject to the provisions of this Act, a supply of goods or services shall be treated as taking place — (a) at the time when an invoice in respect of the supply is issued; or (b) at the time when any payment in respect of the supply is received by the supplier, whichever is the earlier.',
    application: 'Determining which quarterly GST return period (F5) must include output tax for delivered goods or prepaid contracts.',
    practicalRules: [
      'General Rule: Earliest of (1) tax invoice issue date, (2) payment receipt date, and (3) service completion / goods delivery date.',
      '14-Day Rule: If invoice is issued within 14 days after goods delivery or service completion, the invoice date becomes the time of supply (unless payment was received earlier).',
      'Continuous Supplies of Services: Time of supply is the earlier of invoice issuance or payment receipt.',
      'Deposit / Prepayments: GST must be accounted for on deposits or prepayments in the period the cash is received.'
    ],
    canonicalUrl: 'https://sso.agc.gov.sg/Act/GSTA1993?ProvIds=P13-#pr11-',
    tags: ['time of supply', 'section 11', 'tax point', 'invoice date', 'payment date', 'earliest date'],
    sourceStatus: 'VERIFIED',
    sourceType: 'AUTHORITATIVE_SOURCE',
    evidenceTier: 'PRIMARY_SOURCE',
    isVerbatimText: true,
    effectiveDate: '1994-04-01',
    validFrom: '1994-04-01',
    lastVerifiedDate: '2026-09-01',
    reviewAuditCycleDays: 365
  },

  GST_RATE_7_PERCENT: {
    id: 'GST_RATE_7_PERCENT',
    authority: 'IRAS',
    authorityName: 'Inland Revenue Authority of Singapore (IRAS)',
    sourcePublisher: 'Singapore Statutes Online / AGC',
    legalOrStandardInstrument: 'Goods and Services Tax Act 1993',
    actTitle: 'Goods and Services Tax Act 1993',
    actCode: 'GSTA1993',
    sectionOrSchedule: 'Section 16',
    ruleTitle: 'Historical Singapore GST Rate (7% Prior to 1 January 2023)',
    category: 'TAX_GST',
    principle: 'Prior to 1 January 2023, the standard statutory GST rate in Singapore was 7% on all standard-rated taxable supplies of goods and services.',
    verbatimStatuteText: 'Tax shall be charged at the rate of 7% on the supply of goods and services in Singapore.',
    application: 'Historical audit and accounting checks for transactions completed before 1 January 2023.',
    practicalRules: [
      'Rate: 7% on standard-rated supplies.',
      'Validity Period: In force until 31 December 2022.',
      'Superseded: Replaced by 8% GST on 1 January 2023 under Section 16 statutory amendment.'
    ],
    canonicalUrl: 'https://sso.agc.gov.sg/Act/GSTA1993?ProvIds=P13-#pr16-',
    tags: ['7% gst', 'gst rate', 'tax rate', 'rate of tax', 'historical gst', 'gst rate 7', 'gst prior to 2023', 'standard rate'],
    sourceStatus: 'HISTORICAL',
    sourceType: 'AUTHORITATIVE_SOURCE',
    evidenceTier: 'PRIMARY_SOURCE',
    isVerbatimText: true,
    effectiveDate: '2007-07-01',
    validFrom: '2007-07-01',
    validTo: '2022-12-31',
    lastVerifiedDate: '2026-09-01',
    reviewAuditCycleDays: 365,
    supersededByRecordId: 'GST_RATE_8_PERCENT_2023'
  },

  GST_RATE_8_PERCENT_2023: {
    id: 'GST_RATE_8_PERCENT_2023',
    authority: 'IRAS',
    authorityName: 'Inland Revenue Authority of Singapore (IRAS)',
    sourcePublisher: 'Singapore Statutes Online / AGC',
    legalOrStandardInstrument: 'Goods and Services Tax Act 1993',
    actTitle: 'Goods and Services Tax Act 1993',
    actCode: 'GSTA1993',
    sectionOrSchedule: 'Section 16',
    ruleTitle: 'Historical Singapore GST Rate (8% in Calendar Year 2023)',
    category: 'TAX_GST',
    principle: 'From 1 January 2023 to 31 December 2023, the standard statutory GST rate in Singapore was 8% on all standard-rated supplies of goods and services under the first phase of the GST rate increase.',
    verbatimStatuteText: 'Tax shall be charged at the rate of 8% on the supply of goods and services in Singapore made on or after 1 January 2023 but before 1 January 2024.',
    application: 'Historical transactions and audit verification for purchases and sales occurring in calendar year 2023.',
    practicalRules: [
      'Rate: 8% on all standard-rated supplies made between 1 January 2023 and 31 December 2023.',
      'Transitional Rules: Under GST transitional provisions, services spanning across 2023/2024 were prorated or determined by invoice/payment tax points.',
      'Superseded: Replaced by 9% GST on 1 January 2024.'
    ],
    canonicalUrl: 'https://sso.agc.gov.sg/Act/GSTA1993?ProvIds=P13-#pr16-',
    tags: ['8% gst', 'gst rate', 'tax rate', 'rate of tax', '2023 gst', 'historical 8%', 'gst rate 8% 2023', 'standard rate'],
    sourceStatus: 'HISTORICAL',
    sourceType: 'AUTHORITATIVE_SOURCE',
    evidenceTier: 'PRIMARY_SOURCE',
    isVerbatimText: true,
    effectiveDate: '2023-01-01',
    validFrom: '2023-01-01',
    validTo: '2023-12-31',
    lastVerifiedDate: '2026-09-01',
    reviewAuditCycleDays: 365,
    supersededByRecordId: 'GST_RATE_9_PERCENT',
    historicalPredecessorRecordId: 'GST_RATE_7_PERCENT'
  },

  GST_RATE_9_PERCENT: {
    id: 'GST_RATE_9_PERCENT',
    authority: 'IRAS',
    authorityName: 'Inland Revenue Authority of Singapore (IRAS)',
    sourcePublisher: 'Singapore Statutes Online / AGC',
    legalOrStandardInstrument: 'Goods and Services Tax Act 1993',
    actTitle: 'Goods and Services Tax Act 1993',
    actCode: 'GSTA1993',
    sectionOrSchedule: 'Section 16',
    ruleTitle: 'Current Singapore Standard GST Rate (9% from 1 January 2024 Onwards)',
    category: 'TAX_GST',
    principle: 'Effective 1 January 2024 onwards, the standard statutory GST rate in Singapore is 9% on all standard-rated supplies of goods and services.',
    verbatimStatuteText: 'Tax shall be charged at the rate of 9% on the supply of goods and services in Singapore made on or after 1 January 2024.',
    application: 'All current commercial transactions, sales billing, input GST claims, and double-entry accounting in Singapore.',
    practicalRules: [
      'Rate: 9% standard rate effective 1 January 2024 indefinitely.',
      'Input GST Claim: Claimable on qualifying business purchases under Section 19.',
      'Output GST: Collected on domestic taxable supplies and remitted to IRAS via quarterly Form F5.'
    ],
    canonicalUrl: 'https://sso.agc.gov.sg/Act/GSTA1993?ProvIds=P13-#pr16-',
    tags: ['9% gst', 'gst rate', 'tax rate', 'rate of tax', 'current gst rate', 'gst 9 percent', 'standard rate gst', 'standard rate'],
    sourceStatus: 'VERIFIED',
    sourceType: 'AUTHORITATIVE_SOURCE',
    evidenceTier: 'PRIMARY_SOURCE',
    isVerbatimText: true,
    effectiveDate: '2024-01-01',
    validFrom: '2024-01-01',
    lastVerifiedDate: '2026-09-01',
    reviewAuditCycleDays: 365,
    historicalPredecessorRecordId: 'GST_RATE_8_PERCENT_2023'
  },

  // -------------------------------------------------------------
};
