import type { SingaporeStatuteRule } from './types';export const IRAS_STATUTE_RULES: Record<string, SingaporeStatuteRule> = {  // -------------------------------------------------------------
  ITA_SEC14_GENERAL_DEDUCTION: {
    id: 'ITA_SEC14_GENERAL_DEDUCTION',
    authority: 'IRAS',
    authorityName: 'Inland Revenue Authority of Singapore',
    sourcePublisher: 'Singapore Statutes Online / AGC',
    legalOrStandardInstrument: 'Income Tax Act 1947',
    actTitle: 'Income Tax Act 1947',
    actCode: 'ITA1947',
    sectionOrSchedule: 'Section 14(1)',
    ruleTitle: 'General Tax Deductibility of Business Expenses ("Wholly & Exclusively")',
    category: 'TAX_INCOME',
    principle: 'For the purpose of ascertaining the income of any person for any period, there shall be deducted all outgoings and expenses wholly and exclusively incurred during that period by that person in the production of the income.',
    verbatimStatuteText: 'For the purpose of ascertaining the income of any person for any period, there shall be deducted all outgoings and expenses wholly and exclusively incurred during that period by that person in the production of the income.',
    application: 'Operating expenses (rental, staff salaries, utilities, marketing, trade debt provisions) directly related to revenue generation are tax-deductible.',
    practicalRules: [
      'Must be wholly and exclusively incurred in the production of income.',
      'Must not be capital in nature (e.g. initial setup costs, asset purchases).',
      'Must not be prohibited under Section 15 of the Income Tax Act.'
    ],
    canonicalUrl: 'https://sso.agc.gov.sg/Act/ITA1947?ProvIds=pr14-',
    tags: ['tax deduction', 'deductible expenses', 'section 14', 'business expenses', 'p&l deduction'],
    sourceStatus: 'VERIFIED',
    sourceType: 'AUTHORITATIVE_SOURCE',
    evidenceTier: 'PRIMARY_SOURCE',
    isVerbatimText: true,
    effectiveDate: '1948-01-01'
  },

  ITA_SEC15_PROHIBITED_DEDUCTIONS: {
    id: 'ITA_SEC15_PROHIBITED_DEDUCTIONS',
    authority: 'IRAS',
    authorityName: 'Inland Revenue Authority of Singapore & AGC',
    actTitle: 'Income Tax Act 1947',
    actCode: 'ITA1947',
    sectionOrSchedule: 'Section 15(1)',
    ruleTitle: 'Prohibited Non-Deductible Business Expenses',
    category: 'TAX_INCOME',
    principle: 'Notwithstanding any other provisions of this Act, no deduction shall be allowed in respect of: domestic or private expenses; capital sums; improvements; fines and statutory penalties; and non-trade expenses.',
    application: 'Statutory fines (ACRA late filing fines, traffic fines), non-business private expenses paid via company funds, and capital acquisitions cannot be deducted against corporate tax.',
    practicalRules: [
      'Private or domestic expenses of directors/shareholders are disallowed.',
      'Fines and penalties imposed for violation of law are strictly non-deductible.',
      'Income tax paid or payable is non-deductible.',
      'Capital expenditure must be added back in tax computation (capital allowances claimed separately).'
    ],
    canonicalUrl: 'https://sso.agc.gov.sg/Act/ITA1947?ProvIds=P15-#pr15-',
    tags: ['non-deductible', 'prohibited expenses', 'fines', 'section 15', 'add-back']
  },

  ITA_SEC15_1_K_MOTOR_CAR: {
    id: 'ITA_SEC15_1_K_MOTOR_CAR',
    authority: 'IRAS',
    authorityName: 'Inland Revenue Authority of Singapore (IRAS)',
    actTitle: 'Income Tax Act 1947',
    actCode: 'ITA1947',
    sectionOrSchedule: 'Section 15(1)(k)',
    ruleTitle: 'Prohibition of Tax Deduction & Capital Allowances on Private Passenger Motor Cars (S-Plate)',
    category: 'TAX_INCOME',
    principle: 'No deduction shall be allowed for any outgoings and expenses incurred in respect of a motor car registered as a passenger car (whether private or company car, including RU and private hire cars used by staff), nor shall any capital allowance be granted.',
    application: 'Purchasing a private passenger car (S-plate) yields zero tax depreciation. Petrol, parking, road tax, repairs, and ERP incurred on company passenger cars are completely non-deductible.',
    practicalRules: [
      'Company passenger motor cars (S-plate cars) are completely disallowed for Section 14 deductions and Section 19/19A Capital Allowances.',
      'Commercial goods vehicles (G-plate, Y-plate vans, lorries, trucks) ARE 100% eligible for Section 19A Capital Allowances and running expenses are deductible.',
      'Strict add-back of car depreciation and operating expenses is mandatory in Form C-S Tax Computation.'
    ],
    canonicalUrl: 'https://sso.agc.gov.sg/Act/ITA1947?ProvIds=P15-#pr15-',
    tags: ['car expenses', 'passenger car', 'motor car', 's-plate', 'car depreciation', 'section 15(1)(k)']
  },

  ITA_SEC19_19A_CAPITAL_ALLOWANCES: {
    id: 'ITA_SEC19_19A_CAPITAL_ALLOWANCES',
    authority: 'IRAS',
    authorityName: 'Inland Revenue Authority of Singapore (IRAS)',
    actTitle: 'Income Tax Act 1947',
    actCode: 'ITA1947',
    sectionOrSchedule: 'Section 19 & Section 19A',
    ruleTitle: 'Capital Allowances on Plant and Machinery in Lieu of Depreciation',
    category: 'TAX_INCOME',
    principle: 'Accounting depreciation is disallowed for tax. In its place, Capital Allowances (CA) are granted on qualifying plant and machinery used in trade or business.',
    application: 'Companies write off machinery, computers, and office equipment over 1 year (Section 19A(2) 100% write-off for computers & automation equipment, or low-value assets $\\le\\$5,000$ capped at $\\sim\\$30,000$ per YA) or over 3 years straight-line (Section 19A(1)).',
    practicalRules: [
      'Accounting depreciation is added back in tax computation.',
      'Section 19A(1): Accelerated 3-year write-off (33.33% per year).',
      'Section 19A(2): 1-year (100%) accelerated write-off for computers, software, and qualifying automation equipment.',
      'Low-Value Assets: Assets costing $\\le\\$5,000$ each can be fully written off in 1 year, subject to an aggregate limit of $\\$30,000$ per YA.'
    ],
    canonicalUrl: 'https://sso.agc.gov.sg/Act/ITA1947?ProvIds=P16-#pr19A-',
    supplementaryOfficialSources: [{
      title: 'IRAS Capital Allowances',
      url: 'https://www.iras.gov.sg/taxes/corporate-income-tax/income-deductions-for-companies/claiming-allowances/capital-allowances',
      authority: 'IRAS'
    }],
    tags: ['capital allowance', 'depreciation add-back', 'section 19a', 'plant and machinery', 'computers']
  },

  ITA_SUTE_PTE_TAX_EXEMPTION: {
    id: 'ITA_SUTE_PTE_TAX_EXEMPTION',
    authority: 'IRAS',
    authorityName: 'Inland Revenue Authority of Singapore (IRAS)',
    actTitle: 'Income Tax Act 1947',
    actCode: 'ITA1947',
    sectionOrSchedule: 'Section 43 & Tax Exemption Schemes',
    ruleTitle: 'Corporate Income Tax (CIT) Rate & Tax Exemption Schemes (SUTE & PTE)',
    category: 'TAX_INCOME',
    principle: 'Headline corporate income tax rate in Singapore is a flat 17%. Qualifying companies enjoy Start-Up Tax Exemption (SUTE) or Partial Tax Exemption (PTE).',
    application: 'Reduces effective corporate tax significantly below 17%.',
    practicalRules: [
      'Headline Corporate Tax Rate: 17% on chargeable income.',
      'Start-Up Tax Exemption (SUTE) for qualifying new companies (first 3 consecutive YAs):\n  - 75% exemption on the first SGD 100,000 of normal chargeable income\n  - 50% exemption on the next SGD 100,000\n  - Maximum tax exemption of SGD 125,000 (Effective tax on first SGD 200k = ~8.92%).',
      'Partial Tax Exemption (PTE) for all other companies:\n  - 75% exemption on the first SGD 10,000\n  - 50% exemption on the next SGD 190,000\n  - Maximum tax exemption of SGD 102,500.',
      'SUTE Qualifying Conditions: Incorporated in Singapore, tax resident in Singapore, max 20 individual shareholders (or at least 1 individual holding $\\ge 10\\%$ of ordinary shares).'
    ],
    canonicalUrl: 'https://sso.agc.gov.sg/Act/ITA1947?ProvIds=P111-#pr43-',
    tags: ['tax rate', 'sute', 'pte', 'corporate tax', 'tax exemption', '17%']
  },

  IRAS_FORM_CS_LITE_CRITERIA: {
    id: 'IRAS_FORM_CS_LITE_CRITERIA',
    authority: 'IRAS',
    authorityName: 'Inland Revenue Authority of Singapore (IRAS)',
    actTitle: 'IRAS Form C-S/ Form C-S (Lite)/ Form C filing guidance',
    actCode: 'ITA1947',
    sectionOrSchedule: 'Form C-S / Form C-S (Lite) / Form C Guidelines',
    ruleTitle: 'Eligibility Criteria for Form C-S and Form C-S (Lite) Tax Filing',
    category: 'TAX_INCOME',
    principle: 'For YA 2026, Singapore-incorporated companies satisfying the Form C-S eligibility conditions may file a simplified return without attaching financial statements or tax computations. Companies with annual revenue of SGD 200,000 or below that qualify for Form C-S may choose Form C-S (Lite).',
    application: 'Check annual revenue, tax rate of income and disqualifying claims before choosing a return type.',
    practicalRules: [
      'Form C-S (Lite): First satisfy Form C-S conditions; annual revenue must be SGD 200,000 or below.',
      'Form C-S: Singapore-incorporated, annual revenue SGD 5 million or below, income taxable only at the prevailing corporate rate, and no claim for current-year loss/capital-allowance carry-back, group relief, investment allowance, foreign tax credit or tax deducted at source.',
      'The prevailing-rate income condition permits one-tier tax-exempt Singapore dividends and specified foreign-sourced income exempt under Section 13(8); check IRAS guidance for the precise exceptions.',
      'Form C: Use when Form C-S conditions are not met; financial statements and tax computation must be submitted.',
      'Filing Deadline: 30 November of the Year of Assessment (YA) via myTax Portal.'
    ],
    canonicalUrl: 'https://www.iras.gov.sg/taxes/corporate-income-tax/form-c-s-form-c-s-(lite)-form-c-filing/overview-of-form-c-s-form-c-s-(lite)-form-c',
    tags: ['form c-s', 'form c-s lite', 'form c', 'tax filing deadline', 'annual revenue 5m'],
    sourceStatus: 'VERIFIED',
    sourceType: 'CURATED_SUMMARY',
    evidenceTier: 'OFFICIAL_GUIDANCE',
    isVerbatimText: false,
    effectiveDate: '2026-01-01',
    validFrom: '2026-01-01',
    lastVerifiedDate: '2026-09-26',
    reviewAuditCycleDays: 90
  },

  ITA_SEC37_LOSS_CARRY_FORWARD: {
    id: 'ITA_SEC37_LOSS_CARRY_FORWARD',
    authority: 'IRAS',
    authorityName: 'Inland Revenue Authority of Singapore (IRAS)',
    sourcePublisher: 'Singapore Statutes Online / AGC',
    legalOrStandardInstrument: 'Income Tax Act 1947',
    actTitle: 'Income Tax Act 1947',
    actCode: 'ITA1947',
    sectionOrSchedule: 'Section 37',
    ruleTitle: 'Loss Carry-Forward & Substantial Shareholding Continuity Test (50% Continuity)',
    category: 'TAX_INCOME',
    principle: 'Under Section 37(3)(a) of the Income Tax Act 1947, unabsorbed trade losses and capital allowances may be carried forward indefinitely to offset against future taxable income from all sources, subject to the substantial shareholding test (at least 50% continuity of ultimate shareholders as at the relevant comparison dates).',
    verbatimStatuteText: 'There shall be deducted from the statutory income of any person for any year of assessment the amount of a loss incurred by that person in any trade, business, profession or vocation, provided that no deduction shall be allowed to any company unless the Comptroller is satisfied that the shareholders of the company on the last day of the year in which the loss was incurred were substantially the same as the shareholders of the company on the first day of the year of assessment in which the loss is to be deducted.',
    application: 'Corporate tax computation: unabsorbed losses from prior YAs offset current year statutory income if shareholder continuity >= 50% is proven.',
    practicalRules: [
      'Indefinite Carry-Forward: Unabsorbed trade losses carry forward indefinitely until fully utilised.',
      'Substantial Shareholding Test (SST): Shareholders holding >= 50% of paid-up capital/shares must be substantially identical on comparison dates (last day of loss year vs first day of YA of deduction).',
      'Order of Deduction: Unabsorbed capital allowances from prior years are deducted before unabsorbed trade losses.',
      'Shareholding Waiver: Minister or Comptroller may waive SST if substantial change was not for tax benefit.'
    ],
    canonicalUrl: 'https://sso.agc.gov.sg/Act/ITA1947?ProvIds=P19-#pr37-',
    tags: ['loss carry forward', 'section 37', 'tax losses', 'substantial shareholding', 'sst 50%', 'unabsorbed losses'],
    sourceStatus: 'VERIFIED',
    sourceType: 'AUTHORITATIVE_SOURCE',
    evidenceTier: 'PRIMARY_SOURCE',
    isVerbatimText: true,
    effectiveDate: '1948-01-01',
    validFrom: '1948-01-01',
    lastVerifiedDate: '2026-09-01',
    reviewAuditCycleDays: 365
  },

  ITA_SEC37E_LOSS_CARRY_BACK: {
    id: 'ITA_SEC37E_LOSS_CARRY_BACK',
    authority: 'IRAS',
    authorityName: 'Inland Revenue Authority of Singapore (IRAS)',
    sourcePublisher: 'Singapore Statutes Online / AGC',
    legalOrStandardInstrument: 'Income Tax Act 1947',
    actTitle: 'Income Tax Act 1947',
    actCode: 'ITA1947',
    sectionOrSchedule: 'Section 37E',
    ruleTitle: 'Loss Carry-Back Relief Scheme (Cap SGD 100,000 to Immediate Preceding YA)',
    category: 'TAX_INCOME',
    principle: 'Under Section 37E of the Income Tax Act 1947, qualifying businesses may carry back current-year unabsorbed capital allowances and trade losses up to an aggregate cap of SGD 100,000 to offset against the assessable income of the one immediately preceding Year of Assessment, subject to the substantial shareholding test and the same-business test.',
    verbatimStatuteText: 'There shall be deducted from the assessable income of a person for the year of assessment immediately preceding the year of assessment in which the person incurs a qualifying deduction the amount of that qualifying deduction, provided that the total amount of qualifying deductions that may be deducted shall not exceed $100,000.',
    application: 'SMEs facing an operating loss in current year can elect to carry back up to SGD 100,000 loss to the immediate prior YA to claim an immediate corporate tax refund.',
    practicalRules: [
      'Maximum Cap: Capped at an aggregate of SGD 100,000 of qualifying deductions per YA.',
      'Carry-Back Period: Carried back to the 1 immediately preceding Year of Assessment.',
      'Substantial Shareholding & Same Business Test: Entity must satisfy 50% shareholder continuity and same business test (for capital allowances).',
      'Election Deadline: Must be formally elected when e-filing Form C / Form C-S for the loss year.'
    ],
    canonicalUrl: 'https://sso.agc.gov.sg/Act/ITA1947?ProvIds=P19-#pr37E-',
    tags: ['loss carry back', 'section 37e', '100000 cap', 'tax refund', 'carry back relief'],
    sourceStatus: 'VERIFIED',
    sourceType: 'AUTHORITATIVE_SOURCE',
    evidenceTier: 'PRIMARY_SOURCE',
    isVerbatimText: true,
    effectiveDate: '2006-01-01',
    validFrom: '2006-01-01',
    lastVerifiedDate: '2026-09-01',
    reviewAuditCycleDays: 365
  },

  ITA_SEC13W_EQUITY_DISPOSAL_SAFE_HARBOUR: {
    id: 'ITA_SEC13W_EQUITY_DISPOSAL_SAFE_HARBOUR',
    authority: 'IRAS',
    authorityName: 'Inland Revenue Authority of Singapore (IRAS)',
    sourcePublisher: 'Inland Revenue Authority of Singapore (IRAS)',
    legalOrStandardInstrument: 'Income Tax Act 1947',
    actTitle: 'Income Tax Act 1947',
    actCode: 'ITA1947',
    sectionOrSchedule: 'Section 13W',
    ruleTitle: 'Historical Section 13W Treatment for Ordinary-share Disposals Before 2026',
    category: 'TAX_INCOME',
    principle: 'For disposals before 1 January 2026, Section 13W provided certainty of non-taxation for qualifying gains on ordinary shares where the divesting company held at least 20% of the investee ordinary shares for a continuous 24 months before disposal, subject to the statutory exclusions.',
    application: 'Check the disposal date, ordinary-share holding, continuity and exclusions before applying the pre-2026 treatment.',
    practicalRules: [
      'Minimum Shareholding: At least 20% of the ordinary shares of the investee company.',
      'Holding Period: Minimum 24 continuous months immediately preceding the disposal.',
      'Ordinary Shares: Applies to ordinary shares (shares that carry voting, dividend, and surplus asset rights without fixed preference).',
      'Exclusions: Does not apply to unlisted property-holding companies whose main business is holding immovable property in Singapore.'
    ],
    canonicalUrl: 'https://www.iras.gov.sg/media/docs/default-source/e-tax/etaxguide_certainty-of-non-taxation-of-companies-gain-on-disposal-of-equity-investments.pdf',
    tags: ['section 13w', 'safe harbour', 'share disposal', 'capital gain exemption', '20 percent 24 months'],
    sourceStatus: 'HISTORICAL',
    sourceType: 'CURATED_SUMMARY',
    evidenceTier: 'OFFICIAL_GUIDANCE',
    isVerbatimText: false,
    effectiveDate: '2012-06-01',
    validFrom: '2012-06-01',
    validTo: '2025-12-31',
    lastVerifiedDate: '2026-09-26',
    reviewAuditCycleDays: 90
  },

  ITA_SEC13W_EQUITY_DISPOSAL_2026: {
    id: 'ITA_SEC13W_EQUITY_DISPOSAL_2026',
    authority: 'IRAS',
    authorityName: 'Inland Revenue Authority of Singapore (IRAS)',
    sourcePublisher: 'Inland Revenue Authority of Singapore (IRAS)',
    legalOrStandardInstrument: 'Income Tax Act 1947',
    actTitle: 'Income Tax Act 1947',
    actCode: 'ITA1947',
    sectionOrSchedule: 'Section 13W',
    ruleTitle: 'Section 13W Treatment for Ordinary and Qualifying Preference Shares from 2026',
    category: 'TAX_INCOME',
    principle: 'For disposals on or after 1 January 2026, Section 13W can apply to qualifying gains from ordinary shares and qualifying preference shares. The 20% holding requirement over a continuous 24 months may be assessed on a group basis, subject to the detailed conditions and exclusions.',
    application: 'Confirm the share class, disposal date, continuous holding and group holdings before concluding that a gain is outside tax.',
    practicalRules: [
      'Qualifying ordinary shares or preference shares may be covered for disposals from 1 January 2026.',
      'Assess the 20% holding requirement over the 24 months before disposal, including group holdings where eligible.',
      'Check statutory exclusions and the detailed IRAS guidance before treating a gain as non-taxable.'
    ],
    canonicalUrl: 'https://www.iras.gov.sg/media/docs/default-source/e-tax/etaxguide_certainty-of-non-taxation-of-companies-gain-on-disposal-of-equity-investments.pdf',
    tags: ['section 13w', 'safe harbour', 'share disposal', 'preference shares', 'ordinary shares', '20 percent 24 months'],
    sourceStatus: 'VERIFIED',
    sourceType: 'CURATED_SUMMARY',
    evidenceTier: 'OFFICIAL_GUIDANCE',
    isVerbatimText: false,
    effectiveDate: '2026-01-01',
    validFrom: '2026-01-01',
    historicalPredecessorRecordId: 'ITA_SEC13W_EQUITY_DISPOSAL_SAFE_HARBOUR',
    lastVerifiedDate: '2026-09-26',
    reviewAuditCycleDays: 90
  },

  ITA_SEC45_WITHHOLDING_TAX: {
    id: 'ITA_SEC45_WITHHOLDING_TAX',
    authority: 'IRAS',
    authorityName: 'Inland Revenue Authority of Singapore (IRAS)',
    sourcePublisher: 'Inland Revenue Authority of Singapore (IRAS)',
    legalOrStandardInstrument: 'Income Tax Act 1947',
    actTitle: 'Income Tax Act 1947',
    actCode: 'ITA1947',
    sectionOrSchedule: 'Section 45',
    ruleTitle: 'Withholding Tax on Interest, Loan Charges & Indebtedness Paid to Non-Residents',
    category: 'TAX_INCOME',
    principle: 'Interest and other specified loan-related payments to a non-resident may be subject to Singapore withholding tax under Section 45. Confirm Singapore source, recipient status, applicable exemption or treaty relief, the payment date and the applicable rate before concluding that tax must be withheld.',
    application: 'For an intercompany loan payment, confirm the lender’s residence, Singapore nexus, treaty position and the loan purpose before computing withholding tax.',
    practicalRules: [
      'Rate: 15% reduced final withholding tax can apply to qualifying gross interest; another rate or treaty relief may apply depending on the facts.',
      'Payment Deadline: Must e-file Form S45 and remit withheld tax to IRAS by the 15th of the second month following the payment date.',
      'Date of Payment: Deemed paid when credited to payee account, reinvested, accumulated, capitalized, or made available.',
      'Late Payment Penalty: 5% initial late payment penalty plus additional 1% per month up to maximum 15%.'
    ],
    canonicalUrl: 'https://www.iras.gov.sg/taxes/withholding-tax/payments-to-non-resident-company/payments-that-are-subject-to-withholding-tax',
    tags: ['withholding tax', 'section 45', 'interest withholding', 'non-resident interest', '15% final tax'],
    sourceStatus: 'VERIFIED',
    sourceType: 'CURATED_SUMMARY',
    evidenceTier: 'OFFICIAL_GUIDANCE',
    isVerbatimText: false,
    // This curated record summarises current guidance, including the present
    // filing deadline. It does not establish the rules for earlier payments.
    effectiveDate: '2026-01-01',
    validFrom: '2026-01-01',
    lastVerifiedDate: '2026-09-26',
    reviewAuditCycleDays: 90
  },

  ITA_SEC45A_WITHHOLDING_TAX_ROYALTIES: {
    id: 'ITA_SEC45A_WITHHOLDING_TAX_ROYALTIES',
    authority: 'IRAS',
    authorityName: 'Inland Revenue Authority of Singapore (IRAS)',
    sourcePublisher: 'Inland Revenue Authority of Singapore (IRAS)',
    legalOrStandardInstrument: 'Income Tax Act 1947',
    actTitle: 'Income Tax Act 1947',
    actCode: 'ITA1947',
    sectionOrSchedule: 'Section 45A',
    ruleTitle: 'Withholding Tax on Royalties, Technical Fees & Management Charges Paid to Non-Residents',
    category: 'TAX_INCOME',
    principle: 'Withholding tax on royalties, technical services and management fees paid to non-residents depends on the nature of the rights or services, where services are physically performed, recipient residence, treaty position and payment date. Services performed in Singapore can attract non-final withholding at the prevailing corporate income tax rate.',
    application: 'Separate rights-based royalty payments from service fees and identify the portion of services performed in Singapore before applying a rate.',
    practicalRules: [
      'Royalties Rate: The 10% gross-payment final rate may apply where a non-resident derives the royalty through operations outside Singapore; operations in Singapore, treaty relief or an exemption may change the rate and basis.',
      'Management / Technical Service Fees: For services performed in Singapore, non-final withholding at the prevailing corporate income tax rate for the year the services were provided may apply, even if payment occurs in another year; attribute mixed-location services accordingly.',
      'Filing Deadline: 15th of the second month after the date of payment via myTax Portal.',
      'Software Exemption: Commercial off-the-shelf software licenses without copyright acquisition enjoy administrative concession from withholding tax under IRAS e-Tax Guide.'
    ],
    canonicalUrl: 'https://www.iras.gov.sg/taxes/withholding-tax/payments-to-non-resident-company/payments-that-are-subject-to-withholding-tax',
    tags: ['section 45a', 'royalties withholding', 'technical service fees', 'management fees', 'withholding non-resident'],
    sourceStatus: 'VERIFIED',
    sourceType: 'CURATED_SUMMARY',
    evidenceTier: 'OFFICIAL_GUIDANCE',
    isVerbatimText: false,
    effectiveDate: '2026-01-01',
    validFrom: '2026-01-01',
    lastVerifiedDate: '2026-09-26',
    reviewAuditCycleDays: 90
  },

  ITA_SEC14N_RENOVATION_REFURBISHMENT_PRE2025: {
    id: 'ITA_SEC14N_RENOVATION_REFURBISHMENT_PRE2025',
    authority: 'IRAS',
    authorityName: 'Inland Revenue Authority of Singapore (IRAS)',
    sourcePublisher: 'Inland Revenue Authority of Singapore (IRAS)',
    legalOrStandardInstrument: 'Income Tax Act 1947',
    actTitle: 'Income Tax Act 1947',
    actCode: 'ITA1947',
    sectionOrSchedule: 'Section 14N',
    ruleTitle: 'Historical Renovation and Refurbishment Deduction for YAs 2018 to 2024',
    category: 'TAX_INCOME',
    principle: 'For YAs 2018 to 2024, qualifying renovation and refurbishment expenditure under Section 14N was generally deducted over 3 consecutive YAs, subject to the then-applicable SGD 300,000 cap over a 3-year period determined by the first claim. An irrevocable 1-year deduction option applied to qualifying expenditure in the basis periods for YAs 2021, 2022 and 2024.',
    application: 'Identify the YA from the company’s basis period, the first-claim period and any accelerated-deduction election before determining a historical deduction.',
    practicalRules: [
      'The pre-YA 2025 3-year cap period depended on when the first R&R claim was made; do not use the fixed YA 2025–2027 cap period.',
      'A 1-year deduction option was available for qualifying expenditure in the basis periods for YAs 2021, 2022 and 2024.',
      'Designer or professional fees added under the YA 2025 enhancement must not be assumed to qualify in an earlier YA.'
    ],
    canonicalUrl: 'https://www.iras.gov.sg/taxes/corporate-income-tax/income-deductions-for-companies/business-expenses/tax-treatment-of-business-expenses-(m-r)',
    tags: ['renovation deduction', 'section 14n', 'r&r deduction', 'historical renovation', 'YA 2024'],
    sourceStatus: 'HISTORICAL',
    sourceType: 'CURATED_SUMMARY',
    evidenceTier: 'OFFICIAL_GUIDANCE',
    isVerbatimText: false,
    effectiveDate: '2018-01-01',
    validFrom: '2018-01-01',
    validTo: '2024-12-31',
    lastVerifiedDate: '2026-09-26',
    reviewAuditCycleDays: 90
  },

  ITA_SEC14N_RENOVATION_REFURBISHMENT: {
    id: 'ITA_SEC14N_RENOVATION_REFURBISHMENT',
    authority: 'IRAS',
    authorityName: 'Inland Revenue Authority of Singapore (IRAS)',
    sourcePublisher: 'Inland Revenue Authority of Singapore (IRAS)',
    legalOrStandardInstrument: 'Income Tax Act 1947',
    actTitle: 'Income Tax Act 1947',
    actCode: 'ITA1947',
    sectionOrSchedule: 'Section 14N',
    ruleTitle: 'Deduction for Renovation and Refurbishment (R&R) Costs',
    category: 'TAX_INCOME',
    principle: 'Under Section 14N of the Income Tax Act 1947, qualifying non-structural renovation or refurbishment expenditure for a continuing trade, business or profession may be deducted, subject to a SGD 300,000 cap for each fixed 3-year period beginning YA 2025. A 1-year write-off may be elected for qualifying expenditure incurred from YA 2025.',
    application: 'Check the YA, qualifying work, trade continuity, the remaining cap for the fixed 3-year period and the elected claim period before calculating a deduction.',
    practicalRules: [
      'Cap: SGD 300,000 for each fixed 3-year period, beginning YA 2025 to YA 2027.',
      'Deduction Schedule: Normally one-third in each of 3 consecutive YAs; from YA 2025, a 1-year write-off may be elected for qualifying expenditure.',
      'Qualifying Items: General lighting, floor tiles, false ceilings, fixed partitions, wall coverings, doors, plumbing, electrical installations.',
      'Non-Qualifying Items: Structural changes and fine art. Non-structural designer or professional fees may qualify from YA 2025.'
    ],
    canonicalUrl: 'https://www.iras.gov.sg/taxes/corporate-income-tax/income-deductions-for-companies/business-expenses/tax-treatment-of-business-expenses-(m-r)',
    tags: ['renovation deduction', 'section 14n', 'r&r deduction', '300000 cap', 'renovation 3 years'],
    sourceStatus: 'VERIFIED',
    sourceType: 'CURATED_SUMMARY',
    evidenceTier: 'OFFICIAL_GUIDANCE',
    isVerbatimText: false,
    effectiveDate: '2025-01-01',
    validFrom: '2025-01-01',
    historicalPredecessorRecordId: 'ITA_SEC14N_RENOVATION_REFURBISHMENT_PRE2025',
    lastVerifiedDate: '2026-09-26',
    reviewAuditCycleDays: 90
  },

  // -------------------------------------------------------------

  // -------------------------------------------------------------
  ITA_SEC14C_EIS_INNOVATION: {
    id: 'ITA_SEC14C_EIS_INNOVATION',
    authority: 'IRAS',
    authorityName: 'Inland Revenue Authority of Singapore (IRAS)',
    actTitle: 'Income Tax Act 1947',
    actCode: 'ITA1947',
    sectionOrSchedule: 'Section 14C & Section 14D (Enterprise Innovation Scheme)',
    ruleTitle: '400% Enhanced Tax Deduction on Qualifying R&D and Enterprise Innovation Scheme (EIS)',
    category: 'TAX_INCOME',
    principle: 'Under the Enterprise Innovation Scheme (EIS), qualifying businesses enjoy an enhanced 400% tax deduction on up to SGD 400,000 of qualifying expenditure per activity incurred on qualifying R&D, innovation, and IP registration.',
    application: 'Companies undertaking internal product development, software engineering, or filing patents/trademarks in Singapore.',
    practicalRules: [
      'Enhanced Deduction: 400% tax deduction (100% baseline under Section 14C + 300% enhanced under EIS) on qualifying R&D staff costs and consumables.',
      'Expenditure Cap: Capped at SGD 400,000 per qualifying activity per Year of Assessment.',
      'Cash Conversion Option: Qualifying businesses can opt to convert up to SGD 100,000 of total qualifying expenditure across all activities into a non-taxable cash payout at a 20% conversion rate (max SGD 20,000).',
      'Accounting vs Tax Divergence: For financial reporting under SFRS(I) 1-38, development costs meeting all 6 criteria are capitalized as an intangible asset and amortized over time. For tax purposes, qualifying R&D expenses claim the enhanced 400% deduction in the YA incurred.'
    ],
    canonicalUrl: 'https://sso.agc.gov.sg/Act/ITA1947?ProvIds=P15-#pr14C-',
    tags: ['eis', 'enterprise innovation scheme', '400% deduction', 'r&d tax deduction', 'section 14c', 'intangibles tax']
  }
};
