import type { SingaporeStatuteRule } from './types';export const IRAS_STATUTE_RULES: Record<string, SingaporeStatuteRule> = {  // -------------------------------------------------------------
  ITA_SEC14_GENERAL_DEDUCTION: {
    id: 'ITA_SEC14_GENERAL_DEDUCTION',
    authority: 'IRAS',
    authorityName: 'Inland Revenue Authority of Singapore',
    sourcePublisher: 'Singapore Statutes Online / AGC',
    legalOrStandardInstrument: 'Income Tax Act 1947',
    actTitle: 'Income Tax Act 1947',
    actCode: 'ITA1947',
    sectionOrSchedule: 'Section 14(1)',
    ruleTitle: 'General Tax Deductibility of Business Expenses ("Wholly & Exclusively")',
    category: 'TAX_INCOME',
    principle: 'For the purpose of ascertaining the income of any person for any period, there shall be deducted all outgoings and expenses wholly and exclusively incurred during that period by that person in the production of the income.',
    verbatimStatuteText: 'For the purpose of ascertaining the income of any person for any period, there shall be deducted all outgoings and expenses wholly and exclusively incurred during that period by that person in the production of the income.',
    application: 'Operating expenses (rental, staff salaries, utilities, marketing, trade debt provisions) directly related to revenue generation are tax-deductible.',
    practicalRules: [
      'Must be wholly and exclusively incurred in the production of income.',
      'Must not be capital in nature (e.g. initial setup costs, asset purchases).',
      'Must not be prohibited under Section 15 of the Income Tax Act.'
    ],
    canonicalUrl: 'https://sso.agc.gov.sg/Act/ITA1947?ProvIds=pr14-',
    tags: ['tax deduction', 'deductible expenses', 'section 14', 'business expenses', 'p&l deduction'],
    sourceStatus: 'VERIFIED',
    sourceType: 'AUTHORITATIVE_SOURCE',
    evidenceTier: 'PRIMARY_SOURCE',
    isVerbatimText: true,
    effectiveDate: '1948-01-01'
  },

  ITA_SEC15_PROHIBITED_DEDUCTIONS: {
    id: 'ITA_SEC15_PROHIBITED_DEDUCTIONS',
    authority: 'IRAS',
    authorityName: 'Inland Revenue Authority of Singapore & AGC',
    sourcePublisher: 'Singapore Statutes Online / Attorney-General’s Chambers',
    legalOrStandardInstrument: 'Income Tax Act 1947',
    actTitle: 'Income Tax Act 1947',
    actCode: 'ITA1947',
    sectionOrSchedule: 'Section 15(1)',
    ruleTitle: 'Selected Deductions Disallowed Under Section 15',
    category: 'TAX_INCOME',
    principle: 'Section 15(1) disallows specified deductions, including domestic or private expenses; expenses not wholly and exclusively laid out to acquire income; capital withdrawn or amounts employed as capital; capital employed in improvements other than plantation replanting; sums recoverable under insurance or indemnity; specified rent or repair expenses; income tax; and specified motor-car expenses, subject to statutory exceptions. This is a summary of selected limbs, not an exhaustive list.',
    application: 'For a specific expense, identify the relevant Section 15 limb and any statutory exception before deciding whether it is deductible. Capital allowances for qualifying assets are assessed separately from depreciation.',
    practicalRules: [
      'Domestic or private expenses are disallowed under Section 15(1)(a), subject to the specific exception in Section 14(1)(g).',
      'Expenses not wholly and exclusively laid out to acquire income, capital withdrawn or employed as capital, capital employed in improvements other than plantation replanting, and sums recoverable under insurance or indemnity are disallowed under Section 15(1)(b) to (e), subject to the Act’s specific exceptions.',
      'Rent or repair costs for premises not incurred to produce income and Singapore or foreign income tax are disallowed under Section 15(1)(f) and (g).',
      'Specified passenger motor-car outgoings and expenses are dealt with separately under Section 15(1)(k); see the motor-car rule for the vehicle categories and exceptions.'
    ],
    canonicalUrl: 'https://sso.agc.gov.sg/Act/ITA1947?ProvIds=P15-#pr15-',
    tags: ['non-deductible', 'prohibited expenses', 'section 15', 'add-back'],
    sourceStatus: 'VERIFIED',
    sourceType: 'CURATED_SUMMARY',
    evidenceTier: 'CURATED_SUMMARY',
    isVerbatimText: false,
    lastVerifiedDate: '2026-09-26',
    reviewAuditCycleDays: 90
  },

  ITA_SEC15_1_K_MOTOR_CAR: {
    id: 'ITA_SEC15_1_K_MOTOR_CAR',
    authority: 'IRAS',
    authorityName: 'Inland Revenue Authority of Singapore (IRAS)',
    sourcePublisher: 'Singapore Statutes Online / Attorney-General’s Chambers',
    legalOrStandardInstrument: 'Income Tax Act 1947',
    actTitle: 'Income Tax Act 1947',
    actCode: 'ITA1947',
    sectionOrSchedule: 'Section 15(1)(k)',
    ruleTitle: 'Passenger Motor Car Expense and Capital Allowance Restrictions (with Exceptions)',
    category: 'TAX_INCOME',
    principle: 'Section 15(1)(k) generally disallows outgoings and expenses (including employee reimbursements) in respect of qualifying passenger motor cars, subject to vehicle- and business-specific exceptions. Capital allowances on motor cars are governed separately by Sections 19 and 19A and are generally unavailable except under limited vehicle-specific rules. Vehicle category, registration date and use must be checked before deciding whether a deduction or allowance is available.',
    application: 'Identify the vehicle category and registration date, how the car is used, and the type of cost. Distinguish tax depreciation from capital allowances and running-cost deductions; do not infer eligibility from a G/Y plate or the label “commercial vehicle”.',
    practicalRules: [
      'Running expenses for private cars (e.g. S-plated cars) and business cars (e.g. Q- and RU-plated cars registered on or after 1 April 1998) are generally non-deductible even when used for business. Direct costs and employee reimbursements are treated alike.',
      'Transport allowances paid to staff are deductible to the employer but form part of the employees’ taxable employment income. Point-to-point transportation services are distinct from hiring or operating a private car; IRAS generally disallows hired-car costs except where the company carries on a car-hire or driving-instruction business.',
      'Taxi running-expense exception: Section 15(1)(k)(i), subject to Section 15(2D), permits qualifying taxi outgoings and expenses. For expenses incurred on or after 12 November 2018, deduct only amounts attributable to use of the taxi for an “authorised purpose” as defined in Section 14ZA(8). This taxi rule does not itself extend to private-hire cars.',
      'IRAS identifies exceptions for certain foreign-registered cars used exclusively outside Singapore for business, and a capped deduction for motor-vehicle expenses of Q- or RU-plated business cars registered before 1 April 1998. Check the applicable conditions and cap.',
      'Capital allowances are generally unavailable for private and business cars. IRAS identifies exceptions for private-hire cars and instructional cars hired out or used for driving instruction in the business; the Acts also contain other narrowly conditioned exceptions, including for taxis, qualifying foreign-registered cars and specified legacy business service passenger vehicles. Confirm the exact statutory conditions before applying an exception. Qualifying vans, lorries and motorcycles used for business may qualify under Sections 19 or 19A.',
      'Accounting depreciation is not itself a tax deduction. Add it back where the vehicle is within the tax disallowance; assess any capital-allowance exception separately.'
    ],
    canonicalUrl: 'https://sso.agc.gov.sg/Act/ITA1947?ProvIds=P15-#pr15-',
    supplementaryOfficialSources: [
      { title: 'IRAS — Tax Treatment of Business Expenses (Motor Vehicle Expenses)', url: 'https://www.iras.gov.sg/taxes/corporate-income-tax/income-deductions-for-companies/business-expenses/tax-treatment-of-business-expenses-%28m-r%29', authority: 'IRAS' },
      { title: 'IRAS — Capital Allowances (Motor Vehicles)', url: 'https://www.iras.gov.sg/taxes/corporate-income-tax/income-deductions-for-companies/claiming-allowances/capital-allowances', authority: 'IRAS' }
    ],
    tags: ['car expenses', 'passenger car', 'motor car', 's-plate', 'car depreciation', 'section 15(1)(k)'],
    sourceStatus: 'VERIFIED',
    sourceType: 'CURATED_SUMMARY',
    evidenceTier: 'OFFICIAL_GUIDANCE',
    isVerbatimText: false,
    lastVerifiedDate: '2026-09-26',
    reviewAuditCycleDays: 90
  },

  ITA_SEC19_19A_CAPITAL_ALLOWANCES: {
    id: 'ITA_SEC19_19A_CAPITAL_ALLOWANCES',
    authority: 'IRAS',
    authorityName: 'Inland Revenue Authority of Singapore (IRAS)',
    sourcePublisher: 'Inland Revenue Authority of Singapore (IRAS)',
    legalOrStandardInstrument: 'Income Tax Act 1947',
    actTitle: 'Income Tax Act 1947',
    actCode: 'ITA1947',
    sectionOrSchedule: 'Section 19 & Section 19A',
    ruleTitle: 'Capital Allowances on Plant and Machinery in Lieu of Depreciation',
    category: 'TAX_INCOME',
    principle: 'Accounting depreciation is disallowed for tax. In its place, Capital Allowances (CA) are granted on qualifying plant and machinery used in trade or business.',
    application: 'A business may claim capital allowances on qualifying plant and machinery used in its trade or business, using an available write-off method. Eligibility and the applicable method depend on the asset and the relevant Year of Assessment.',
    practicalRules: [
      'Accounting depreciation is added back in tax computation.',
      'Section 19A(1): Accelerated 3-year write-off (33.33% per year).',
      'Section 19A(2): 1-year (100%) write-off is available for computers and prescribed automation equipment; prescribed automation equipment can include specified computer software.',
      'Section 19A(10A): A 1-year write-off is available for low-value assets costing no more than SGD 5,000 each, subject to an aggregate SGD 30,000 limit per YA.',
      'IRAS also describes a 2-year write-off option for assets acquired during basis periods for YAs 2021, 2022 and 2024; check the relevant YA and statutory conditions.'
    ],
    canonicalUrl: 'https://sso.agc.gov.sg/Act/ITA1947?ProvIds=P16-#pr19A-',
    supplementaryOfficialSources: [{
      title: 'IRAS Capital Allowances',
      url: 'https://www.iras.gov.sg/taxes/corporate-income-tax/income-deductions-for-companies/claiming-allowances/capital-allowances',
      authority: 'IRAS'
    }],
    tags: ['capital allowance', 'depreciation add-back', 'section 19a', 'plant and machinery', 'computers'],
    sourceStatus: 'VERIFIED',
    sourceType: 'CURATED_SUMMARY',
    evidenceTier: 'OFFICIAL_GUIDANCE',
    isVerbatimText: false,
    lastVerifiedDate: '2026-09-26',
    reviewAuditCycleDays: 90
  },

  ITA_SUTE_PTE_TAX_EXEMPTION: {
    id: 'ITA_SUTE_PTE_TAX_EXEMPTION',
    authority: 'IRAS',
    authorityName: 'Inland Revenue Authority of Singapore (IRAS)',
    actTitle: 'Income Tax Act 1947',
    actCode: 'ITA1947',
    sectionOrSchedule: 'Section 43 & Tax Exemption Schemes',
    ruleTitle: 'Corporate Income Tax (CIT) Rate & Tax Exemption Schemes (SUTE & PTE)',
    category: 'TAX_INCOME',
    principle: 'Headline corporate income tax rate in Singapore is a flat 17%. Qualifying companies enjoy Start-Up Tax Exemption (SUTE) or Partial Tax Exemption (PTE).',
    application: 'Reduces effective corporate tax significantly below 17%.',
    practicalRules: [
      'Headline Corporate Tax Rate: 17% on chargeable income.',
      'Start-Up Tax Exemption (SUTE) for qualifying new companies (first 3 consecutive YAs):\n  - 75% exemption on the first SGD 100,000 of normal chargeable income\n  - 50% exemption on the next SGD 100,000\n  - Maximum tax exemption of SGD 125,000 (Effective tax on first SGD 200k = ~8.92%).',
      'Partial Tax Exemption (PTE) for all other companies:\n  - 75% exemption on the first SGD 10,000\n  - 50% exemption on the next SGD 190,000\n  - Maximum tax exemption of SGD 102,500.',
      'SUTE Qualifying Conditions: Incorporated in Singapore, tax resident in Singapore, max 20 individual shareholders (or at least 1 individual holding $\\ge 10\\%$ of ordinary shares).'
    ],
    canonicalUrl: 'https://sso.agc.gov.sg/Act/ITA1947?ProvIds=P111-#pr43-',
    tags: ['tax rate', 'sute', 'pte', 'corporate tax', 'tax exemption', '17%']
  },

  IRAS_FORM_CS_LITE_CRITERIA: {
    id: 'IRAS_FORM_CS_LITE_CRITERIA',
    authority: 'IRAS',
    authorityName: 'Inland Revenue Authority of Singapore (IRAS)',
    actTitle: 'IRAS Form C-S/ Form C-S (Lite)/ Form C filing guidance',
    actCode: 'ITA1947',
    sectionOrSchedule: 'Form C-S / Form C-S (Lite) / Form C Guidelines',
    ruleTitle: 'Eligibility Criteria for Form C-S and Form C-S (Lite) Tax Filing',
    category: 'TAX_INCOME',
    principle: 'For YA 2026, Singapore-incorporated companies satisfying the Form C-S eligibility conditions may file a simplified return without attaching financial statements or tax computations. Companies with annual revenue of SGD 200,000 or below that qualify for Form C-S may choose Form C-S (Lite).',
    application: 'Check annual revenue, tax rate of income and disqualifying claims before choosing a return type.',
    practicalRules: [
      'Form C-S (Lite): First satisfy Form C-S conditions; annual revenue must be SGD 200,000 or below.',
      'Form C-S: Singapore-incorporated, annual revenue SGD 5 million or below, income taxable only at the prevailing corporate rate, and no claim for current-year loss/capital-allowance carry-back, group relief, investment allowance, foreign tax credit or tax deducted at source.',
      'The prevailing-rate income condition permits one-tier tax-exempt Singapore dividends and specified foreign-sourced income exempt under Section 13(8); check IRAS guidance for the precise exceptions.',
      'Form C: Use when Form C-S conditions are not met; financial statements and tax computation must be submitted.',
      'Filing Deadline: 30 November of the Year of Assessment (YA) via myTax Portal.'
    ],
    canonicalUrl: 'https://www.iras.gov.sg/taxes/corporate-income-tax/form-c-s-form-c-s-(lite)-form-c-filing/overview-of-form-c-s-form-c-s-(lite)-form-c',
    tags: ['form c-s', 'form c-s lite', 'form c', 'tax filing deadline', 'annual revenue 5m'],
    sourceStatus: 'VERIFIED',
    sourceType: 'CURATED_SUMMARY',
    evidenceTier: 'OFFICIAL_GUIDANCE',
    isVerbatimText: false,
    effectiveDate: '2026-01-01',
    validFrom: '2026-01-01',
    lastVerifiedDate: '2026-09-26',
    reviewAuditCycleDays: 90
  },

  ITA_SEC37_LOSS_CARRY_FORWARD: {
    id: 'ITA_SEC37_LOSS_CARRY_FORWARD',
    authority: 'IRAS',
    authorityName: 'Inland Revenue Authority of Singapore (IRAS)',
    sourcePublisher: 'Inland Revenue Authority of Singapore (IRAS)',
    legalOrStandardInstrument: 'Income Tax Act 1947',
    actTitle: 'Income Tax Act 1947',
    actCode: 'ITA1947',
    sectionOrSchedule: 'Section 37',
    ruleTitle: 'Loss and Capital Allowance Carry-Forward Conditions and Shareholding Dates',
    category: 'TAX_INCOME',
    principle: 'Unutilised trade losses and capital allowances may generally be carried forward indefinitely, subject to the shareholding test at the relevant dates. The first comparison date differs: losses use the last day of the calendar year in which the loss was incurred, while capital allowances use the last day of the YA in which they arose. Capital allowances also require continuity of the same trade or business and no change in principal activities.',
    application: 'For each item, identify whether it is a trade loss or capital allowance and its year of origin. Compare the shareholders and their holdings on the matching origin date and the first day of the YA of deduction. For capital allowances, also verify the same-business and principal-activity conditions.',
    practicalRules: [
      'Carry-forward: Unutilised trade losses and capital allowances can generally be carried forward indefinitely, subject to their separate qualifying conditions and the shareholding test.',
      'Trade-loss comparison dates: The last day of the calendar year in which the loss was incurred and the first day of the YA in which it is deducted.',
      'Capital-allowance comparison dates: The last day of the YA in which the allowance arose and the first day of the YA in which it is deducted.',
      'Shareholding test: Compare common shareholders’ aggregate percentage at those two dates. The test is met where the same shareholders collectively hold at least 50% at both dates; ultimate holding company shareholders are considered where applicable.',
      'Capital allowances only: The company must continue the same trade or business for which the allowances were granted and have no change in its principal activities. These are not stated as carry-forward conditions for trade losses.',
      'A waiver of the shareholding test may be available in qualifying circumstances; do not assume it applies.'
    ],
    canonicalUrl: 'https://www.iras.gov.sg/taxes/corporate-income-tax/income-deductions-for-companies/unutilised-items-%28capital-allowances-trade-losses-donations%29',
    tags: ['loss carry forward', 'section 37', 'tax losses', 'substantial shareholding', 'sst 50%', 'unabsorbed losses'],
    sourceStatus: 'VERIFIED',
    sourceType: 'CURATED_SUMMARY',
    evidenceTier: 'OFFICIAL_GUIDANCE',
    isVerbatimText: false,
    effectiveDate: '1948-01-01',
    validFrom: '1948-01-01',
    lastVerifiedDate: '2026-09-26',
    reviewAuditCycleDays: 365
  },

  ITA_SEC37E_LOSS_CARRY_BACK: {
    id: 'ITA_SEC37E_LOSS_CARRY_BACK',
    authority: 'IRAS',
    authorityName: 'Inland Revenue Authority of Singapore (IRAS)',
    sourcePublisher: 'Singapore Statutes Online / AGC',
    legalOrStandardInstrument: 'Income Tax Act 1947',
    actTitle: 'Income Tax Act 1947',
    actCode: 'ITA1947',
    sectionOrSchedule: 'Section 37E',
    ruleTitle: 'Loss Carry-Back Relief Scheme (Cap SGD 100,000 to Immediate Preceding YA)',
    category: 'TAX_INCOME',
    principle: 'Under Section 37E of the Income Tax Act 1947, qualifying businesses may carry back current-year unabsorbed capital allowances and trade losses up to an aggregate cap of SGD 100,000 to offset against the assessable income of the one immediately preceding Year of Assessment, subject to the substantial shareholding test and the same-business test.',
    verbatimStatuteText: 'There shall be deducted from the assessable income of a person for the year of assessment immediately preceding the year of assessment in which the person incurs a qualifying deduction the amount of that qualifying deduction, provided that the total amount of qualifying deductions that may be deducted shall not exceed $100,000.',
    application: 'SMEs facing an operating loss in current year can elect to carry back up to SGD 100,000 loss to the immediate prior YA to claim an immediate corporate tax refund.',
    practicalRules: [
      'Maximum Cap: Capped at an aggregate of SGD 100,000 of qualifying deductions per YA.',
      'Carry-Back Period: Carried back to the 1 immediately preceding Year of Assessment.',
      'Substantial Shareholding & Same Business Test: Entity must satisfy 50% shareholder continuity and same business test (for capital allowances).',
      'Election Deadline: Must be formally elected when e-filing Form C / Form C-S for the loss year.'
    ],
    canonicalUrl: 'https://sso.agc.gov.sg/Act/ITA1947?ProvIds=P19-#pr37E-',
    tags: ['loss carry back', 'section 37e', '100000 cap', 'tax refund', 'carry back relief'],
    sourceStatus: 'VERIFIED',
    sourceType: 'AUTHORITATIVE_SOURCE',
    evidenceTier: 'PRIMARY_SOURCE',
    isVerbatimText: true,
    effectiveDate: '2006-01-01',
    validFrom: '2006-01-01',
    lastVerifiedDate: '2026-09-01',
    reviewAuditCycleDays: 365
  },

  ITA_SEC13W_EQUITY_DISPOSAL_SAFE_HARBOUR: {
    id: 'ITA_SEC13W_EQUITY_DISPOSAL_SAFE_HARBOUR',
    authority: 'IRAS',
    authorityName: 'Inland Revenue Authority of Singapore (IRAS)',
    sourcePublisher: 'Inland Revenue Authority of Singapore (IRAS)',
    legalOrStandardInstrument: 'Income Tax Act 1947',
    actTitle: 'Income Tax Act 1947',
    actCode: 'ITA1947',
    sectionOrSchedule: 'Section 13W',
    ruleTitle: 'Historical Section 13W Treatment for Ordinary-share Disposals Before 2026',
    category: 'TAX_INCOME',
    principle: 'For disposals before 1 January 2026, Section 13W provided certainty of non-taxation for qualifying gains on ordinary shares where the divesting company held at least 20% of the investee ordinary shares for a continuous 24 months before disposal, subject to the statutory exclusions.',
    application: 'Check the disposal date, ordinary-share holding, continuity and exclusions before applying the pre-2026 treatment.',
    practicalRules: [
      'Minimum Shareholding: At least 20% of the ordinary shares of the investee company.',
      'Holding Period: Minimum 24 continuous months immediately preceding the disposal.',
      'Ordinary Shares: Applies to ordinary shares (shares that carry voting, dividend, and surplus asset rights without fixed preference).',
      'Property exclusions depend on disposal date and investee facts. For non-listed shares disposed before 1 June 2022, exclusions covered trading Singapore immovable property and principally holding Singapore immovable property with passive or no income; property development and qualifying Section 10D letting businesses were not excluded on that basis.',
      'For non-listed shares disposed on or after 1 June 2022, exclusions cover trading or principally holding immovable property anywhere with passive or no income, and property development in Singapore or elsewhere. The property-development exclusion has an exception where the developed property is used in the investee’s own business to derive trade income and no development activity occurred in the preceding 60 months. Other statutory exclusions also apply.',
      'The pre-2026 20% test is met by the divesting company itself; do not aggregate group holdings for this historical period.'
    ],
    canonicalUrl: 'https://www.iras.gov.sg/media/docs/default-source/e-tax/etaxguide_certainty-of-non-taxation-of-companies-gain-on-disposal-of-equity-investments.pdf',
    tags: ['section 13w', 'safe harbour', 'share disposal', 'capital gain exemption', '20 percent 24 months'],
    sourceStatus: 'HISTORICAL',
    sourceType: 'CURATED_SUMMARY',
    evidenceTier: 'OFFICIAL_GUIDANCE',
    isVerbatimText: false,
    effectiveDate: '2012-06-01',
    validFrom: '2012-06-01',
    validTo: '2025-12-31',
    lastVerifiedDate: '2026-09-26',
    reviewAuditCycleDays: 90
  },

  ITA_SEC13W_EQUITY_DISPOSAL_2026: {
    id: 'ITA_SEC13W_EQUITY_DISPOSAL_2026',
    authority: 'IRAS',
    authorityName: 'Inland Revenue Authority of Singapore (IRAS)',
    sourcePublisher: 'Inland Revenue Authority of Singapore (IRAS)',
    legalOrStandardInstrument: 'Income Tax Act 1947',
    actTitle: 'Income Tax Act 1947',
    actCode: 'ITA1947',
    sectionOrSchedule: 'Section 13W',
    ruleTitle: 'Section 13W Treatment for Ordinary and Qualifying Preference Shares from 2026',
    category: 'TAX_INCOME',
    principle: 'For disposals on or after 1 January 2026, Section 13W may exempt qualifying gains from ordinary shares and qualifying preference shares held at the required 20% level for a continuous 24 months immediately before disposal. A group assessment is conditional on the detailed statutory group criteria and does not apply to a divesting registered business trust or variable capital company; other exclusions also apply.',
    application: 'Confirm the share class, disposal date, continuous holding and group holdings before concluding that a gain is outside tax.',
    practicalRules: [
      'Qualifying ordinary shares or preference shares may be covered for disposals from 1 January 2026.',
      'The 20% threshold refers to the total paid-up share capital of ordinary shares and qualifying preference shares. The relevant class must be held continuously for at least 24 months immediately before disposal.',
      'First test the divesting company on a standalone basis. If it does not meet the threshold, aggregate related-company holdings only where the detailed same-group and continuous-period tests are met. Group assessment is unavailable where the divesting company is a registered business trust or a variable capital company.',
      'For non-listed investees, apply the property-related exclusions according to the disposal date, including the post-1 June 2022 trading, passive-holding and 60-month property-development conditions and their exception. Also check excluded-divesting-company and other statutory exclusions before treating a gain as exempt.'
    ],
    canonicalUrl: 'https://www.iras.gov.sg/media/docs/default-source/e-tax/etaxguide_certainty-of-non-taxation-of-companies-gain-on-disposal-of-equity-investments.pdf',
    tags: ['section 13w', 'safe harbour', 'share disposal', 'preference shares', 'ordinary shares', '20 percent 24 months'],
    sourceStatus: 'VERIFIED',
    sourceType: 'CURATED_SUMMARY',
    evidenceTier: 'OFFICIAL_GUIDANCE',
    isVerbatimText: false,
    effectiveDate: '2026-01-01',
    validFrom: '2026-01-01',
    historicalPredecessorRecordId: 'ITA_SEC13W_EQUITY_DISPOSAL_SAFE_HARBOUR',
    lastVerifiedDate: '2026-09-26',
    reviewAuditCycleDays: 90
  },

  ITA_SEC45_WITHHOLDING_TAX: {
    id: 'ITA_SEC45_WITHHOLDING_TAX',
    authority: 'IRAS',
    authorityName: 'Inland Revenue Authority of Singapore (IRAS)',
    sourcePublisher: 'Inland Revenue Authority of Singapore (IRAS)',
    legalOrStandardInstrument: 'Income Tax Act 1947',
    actTitle: 'Income Tax Act 1947',
    actCode: 'ITA1947',
    sectionOrSchedule: 'Section 45',
    ruleTitle: 'Withholding Tax on Interest, Loan Charges & Indebtedness Paid to Non-Residents',
    category: 'TAX_INCOME',
    principle: 'Interest and other specified loan-related payments to a non-resident may be subject to Singapore withholding tax under Section 45. Confirm Singapore source, recipient status, applicable exemption or treaty relief, the payment date and the applicable rate before concluding that tax must be withheld.',
    application: 'For an intercompany loan payment, confirm the lender’s residence, Singapore nexus, treaty position and the loan purpose before computing withholding tax.',
    practicalRules: [
      'Rate: 15% reduced final withholding tax can apply to qualifying gross interest; another rate or treaty relief may apply depending on the facts.',
      'Date of Payment (except director fees): Use the earliest of (a) when payment is due and payable under the agreement or contract, or the invoice date if there is no agreement or contract, (b) when it is credited to the non-resident’s or designated account, and (c) actual payment. Credit terms do not defer the date.',
      'Filing and Payment Deadline: File and pay by the 15th of the second month from the applicable date of payment. Director-fee timing has separate rules.',
      'Late Payment Penalty: 5% initial late payment penalty plus additional 1% per month up to maximum 15%.'
    ],
    canonicalUrl: 'https://www.iras.gov.sg/taxes/withholding-tax/payments-to-non-resident-company/payments-that-are-subject-to-withholding-tax',
    supplementaryOfficialSources: [{ title: 'IRAS — Withholding Tax Filing and Payment Due Date', url: 'https://www.iras.gov.sg/taxes/withholding-tax/withholding-tax-filing/withholding-tax-filing-and-payment-due-date', authority: 'IRAS' }],
    tags: ['withholding tax', 'section 45', 'interest withholding', 'non-resident interest', '15% final tax'],
    sourceStatus: 'VERIFIED',
    sourceType: 'CURATED_SUMMARY',
    evidenceTier: 'OFFICIAL_GUIDANCE',
    isVerbatimText: false,
    // This curated record summarises current guidance, including the present
    // filing deadline. It does not establish the rules for earlier payments.
    effectiveDate: '2026-01-01',
    validFrom: '2026-01-01',
    lastVerifiedDate: '2026-09-26',
    reviewAuditCycleDays: 90
  },

  ITA_SEC45A_WITHHOLDING_TAX_ROYALTIES: {
    id: 'ITA_SEC45A_WITHHOLDING_TAX_ROYALTIES',
    authority: 'IRAS',
    authorityName: 'Inland Revenue Authority of Singapore (IRAS)',
    sourcePublisher: 'Inland Revenue Authority of Singapore (IRAS)',
    legalOrStandardInstrument: 'Income Tax Act 1947',
    actTitle: 'Income Tax Act 1947',
    actCode: 'ITA1947',
    sectionOrSchedule: 'Section 45A',
    ruleTitle: 'Withholding Tax on Royalties, Technical Fees & Management Charges Paid to Non-Residents',
    category: 'TAX_INCOME',
    principle: 'Withholding tax on royalties, technical services and management fees paid to non-residents depends on the nature of the rights or services, where services are physically performed, recipient residence, treaty position and payment date. Services performed in Singapore can attract non-final withholding at the prevailing corporate income tax rate.',
    application: 'Separate rights-based royalty payments from service fees and identify the portion of services performed in Singapore before applying a rate.',
    practicalRules: [
      'Royalties Rate: The 10% gross-payment final rate may apply where a non-resident derives the royalty through operations outside Singapore; operations in Singapore, treaty relief or an exemption may change the rate and basis.',
      'Management / Technical Service Fees: For services performed in Singapore, non-final withholding at the prevailing corporate income tax rate for the year the services were provided may apply, even if payment occurs in another year; attribute mixed-location services accordingly.',
      'Date of Payment (except director fees): Earliest of when payment is due and payable under the agreement or contract, or the invoice date if there is no agreement or contract; when credited to the non-resident’s or designated account; and actual payment. Credit terms do not defer the date.',
      'Filing Deadline: File and pay by the 15th of the second month after the applicable date of payment via myTax Portal. Director-fee timing has separate rules.',
      'Software Exemption: Commercial off-the-shelf software licenses without copyright acquisition enjoy administrative concession from withholding tax under IRAS e-Tax Guide.'
    ],
    canonicalUrl: 'https://www.iras.gov.sg/taxes/withholding-tax/payments-to-non-resident-company/payments-that-are-subject-to-withholding-tax',
    supplementaryOfficialSources: [{ title: 'IRAS — Withholding Tax Filing and Payment Due Date', url: 'https://www.iras.gov.sg/taxes/withholding-tax/withholding-tax-filing/withholding-tax-filing-and-payment-due-date', authority: 'IRAS' }],
    tags: ['section 45a', 'royalties withholding', 'technical service fees', 'management fees', 'withholding non-resident'],
    sourceStatus: 'VERIFIED',
    sourceType: 'CURATED_SUMMARY',
    evidenceTier: 'OFFICIAL_GUIDANCE',
    isVerbatimText: false,
    effectiveDate: '2026-01-01',
    validFrom: '2026-01-01',
    lastVerifiedDate: '2026-09-26',
    reviewAuditCycleDays: 90
  },

  ITA_SEC14N_RENOVATION_REFURBISHMENT_PRE2025: {
    id: 'ITA_SEC14N_RENOVATION_REFURBISHMENT_PRE2025',
    authority: 'IRAS',
    authorityName: 'Inland Revenue Authority of Singapore (IRAS)',
    sourcePublisher: 'Inland Revenue Authority of Singapore (IRAS)',
    legalOrStandardInstrument: 'Income Tax Act 1947',
    actTitle: 'Income Tax Act 1947',
    actCode: 'ITA1947',
    sectionOrSchedule: 'Section 14N',
    ruleTitle: 'Historical Renovation and Refurbishment Deduction for YAs 2018 to 2024',
    category: 'TAX_INCOME',
    principle: 'For YAs 2018 to 2024, qualifying renovation and refurbishment expenditure under Section 14N was generally deducted over 3 consecutive YAs, subject to the then-applicable SGD 300,000 cap over a 3-year period determined by the first claim. An irrevocable 1-year deduction option applied to qualifying expenditure in the basis periods for YAs 2021, 2022 and 2024.',
    application: 'Identify the YA from the company’s basis period, the first-claim period and any accelerated-deduction election before determining a historical deduction.',
    practicalRules: [
      'The pre-YA 2025 3-year cap period depended on when the first R&R claim was made; do not use the fixed YA 2025–2027 cap period.',
      'A 1-year deduction option was available for qualifying expenditure in the basis periods for YAs 2021, 2022 and 2024.',
      'Designer or professional fees added under the YA 2025 enhancement must not be assumed to qualify in an earlier YA.'
    ],
    canonicalUrl: 'https://www.iras.gov.sg/taxes/corporate-income-tax/income-deductions-for-companies/business-expenses/tax-treatment-of-business-expenses-(m-r)',
    tags: ['renovation deduction', 'section 14n', 'r&r deduction', 'historical renovation', 'YA 2024'],
    sourceStatus: 'HISTORICAL',
    sourceType: 'CURATED_SUMMARY',
    evidenceTier: 'OFFICIAL_GUIDANCE',
    isVerbatimText: false,
    effectiveDate: '2018-01-01',
    validFrom: '2018-01-01',
    validTo: '2024-12-31',
    lastVerifiedDate: '2026-09-26',
    reviewAuditCycleDays: 90
  },

  ITA_SEC14N_RENOVATION_REFURBISHMENT: {
    id: 'ITA_SEC14N_RENOVATION_REFURBISHMENT',
    authority: 'IRAS',
    authorityName: 'Inland Revenue Authority of Singapore (IRAS)',
    sourcePublisher: 'Inland Revenue Authority of Singapore (IRAS)',
    legalOrStandardInstrument: 'Income Tax Act 1947',
    actTitle: 'Income Tax Act 1947',
    actCode: 'ITA1947',
    sectionOrSchedule: 'Section 14N',
    ruleTitle: 'Deduction for Renovation and Refurbishment (R&R) Costs',
    category: 'TAX_INCOME',
    principle: 'Under Section 14N of the Income Tax Act 1947, qualifying non-structural renovation or refurbishment expenditure for a continuing trade, business or profession may be deducted, subject to a SGD 300,000 cap for each fixed 3-year period beginning YA 2025. For the first fixed period, YA 2025 to YA 2027, a taxpayer whose existing relevant period does not coincide with that period receives a refreshed SGD 300,000 cap. A 1-year write-off may be elected for qualifying expenditure incurred from YA 2025.',
    application: 'Check the YA from the company’s basis period, qualifying work, trade continuity, the remaining fixed-period cap, whether the transitional refreshed cap applies, and any irrevocable 1-year election before calculating a deduction.',
    practicalRules: [
      'Cap: SGD 300,000 for each fixed 3-year period: YA 2025–2027, YA 2028–2030, YA 2031–2033, and each later consecutive period.',
      'YA 2025 transition: A taxpayer whose existing relevant 3-year period does not coincide with YA 2025–2027 receives a refreshed SGD 300,000 cap for that first fixed period. Do not carry the old rolling-cap balance forward as if no transition applied.',
      'No proration on commencement: A taxpayer that starts carrying on a trade or business during a fixed 3-year period may use the full SGD 300,000 cap for that period. For example, a company commencing business in YA 2026 may use the full cap across YAs 2026 and 2027; do not prorate it for the shorter operating period.',
      'Deduction Schedule: Normally one-third in each of 3 consecutive YAs beginning with the YA relating to the basis period in which costs were first incurred. A 1-year write-off may be elected for qualifying expenditure incurred from YA 2025; the election is irrevocable.',
      'Qualifying Items: General lighting, floor tiles, false ceilings, fixed partitions, wall coverings, doors, plumbing, electrical installations.',
      'Non-Qualifying Items: Structural changes and fine art. Non-structural designer or professional fees may qualify from YA 2025.',
      'No double deduction: Costs qualifying as repairs under Section 14(1)(c) or as plant and machinery under Sections 19 or 19A are claimed under those provisions, not again under Section 14N.'
    ],
    canonicalUrl: 'https://www.iras.gov.sg/taxes/corporate-income-tax/income-deductions-for-companies/business-expenses/tax-treatment-of-business-expenses-(m-r)',
    supplementaryOfficialSources: [{ title: 'IRAS — Tax Deduction for Renovation or Refurbishment Works Done to Business Premises', url: 'https://www.iras.gov.sg/media/docs/default-source/e-tax/etaxguide_it_deduction_r_r_costs.pdf?sfvrsn=7d6cbeea_34', authority: 'IRAS' }],
    tags: ['renovation deduction', 'section 14n', 'r&r deduction', '300000 cap', 'renovation 3 years'],
    sourceStatus: 'VERIFIED',
    sourceType: 'CURATED_SUMMARY',
    evidenceTier: 'OFFICIAL_GUIDANCE',
    isVerbatimText: false,
    effectiveDate: '2025-01-01',
    validFrom: '2025-01-01',
    historicalPredecessorRecordId: 'ITA_SEC14N_RENOVATION_REFURBISHMENT_PRE2025',
    lastVerifiedDate: '2026-09-26',
    reviewAuditCycleDays: 90
  },

  // -------------------------------------------------------------

  // -------------------------------------------------------------
  ITA_SEC14C_EIS_INNOVATION: {
    id: 'ITA_SEC14C_EIS_INNOVATION',
    authority: 'IRAS',
    authorityName: 'Inland Revenue Authority of Singapore (IRAS)',
    actTitle: 'Income Tax Act 1947',
    actCode: 'ITA1947',
    sectionOrSchedule: 'Section 14C & Section 14D (Enterprise Innovation Scheme)',
    ruleTitle: '400% Enhanced Tax Deduction on Qualifying R&D and Enterprise Innovation Scheme (EIS)',
    category: 'TAX_INCOME',
    principle: 'Under the Enterprise Innovation Scheme (EIS), qualifying businesses enjoy an enhanced 400% tax deduction on up to SGD 400,000 of qualifying expenditure per activity incurred on qualifying R&D, innovation, and IP registration.',
    application: 'Companies undertaking internal product development, software engineering, or filing patents/trademarks in Singapore.',
    practicalRules: [
      'Enhanced Deduction: 400% tax deduction (100% baseline under Section 14C + 300% enhanced under EIS) on qualifying R&D staff costs and consumables.',
      'Expenditure Cap: Capped at SGD 400,000 per qualifying activity per Year of Assessment.',
      'Cash Conversion Option: Qualifying businesses can opt to convert up to SGD 100,000 of total qualifying expenditure across all activities into a non-taxable cash payout at a 20% conversion rate (max SGD 20,000).',
      'Accounting vs Tax Divergence: For financial reporting under SFRS(I) 1-38, development costs meeting all 6 criteria are capitalized as an intangible asset and amortized over time. For tax purposes, qualifying R&D expenses claim the enhanced 400% deduction in the YA incurred.'
    ],
    canonicalUrl: 'https://sso.agc.gov.sg/Act/ITA1947?ProvIds=P15-#pr14C-',
    tags: ['eis', 'enterprise innovation scheme', '400% deduction', 'r&d tax deduction', 'section 14c', 'intangibles tax']
  }
};
