import type { SingaporeStatuteRule } from './types';export const MOM_STATUTE_RULES: Record<string, SingaporeStatuteRule> = {  // -------------------------------------------------------------
  MOM_SEC21_SALARY_TIMELINES: {
    id: 'MOM_SEC21_SALARY_TIMELINES',
    authority: 'MOM',
    authorityName: 'Ministry of Manpower (MOM)',
    actTitle: 'Employment Act 1968',
    actCode: 'EA1968',
    sectionOrSchedule: 'Section 21 & Section 22',
    ruleTitle: 'Statutory Salary and Overtime Payment Timelines (Within 7 / 14 Days)',
    category: 'MOM_LABOUR',
    principle: 'An employer must pay salary to employees at least once a month and within 7 days after the end of the salary period. Overtime pay must be paid within 14 days after the salary period.',
    application: 'Companies paying monthly salary must ensure bank transfers settle by the 7th of the following calendar month.',
    practicalRules: [
      'Basic Salary: Must be disbursed within 7 calendar days after the end of the salary period.',
      'Overtime Pay: Must be paid within 14 calendar days after the end of the salary period.',
      'Termination of Service by Employer: All outstanding salary and accumulated benefits must be paid on the last day of employment, or within 3 working days if notice cannot be served.',
      'Itemised Pay Slips: Mandatory under Section 96 of the Employment Act to provide itemised pay slips with every salary payment.'
    ],
    canonicalUrl: 'https://sso.agc.gov.sg/Act/EmA1968?ProvIds=P13-#pr21-',
    tags: ['salary deadline', '7 days', 'overtime payment deadline', 'itemised payslip', 'section 21'],
    sourceStatus: 'VERIFIED',
    sourceType: 'AUTHORITATIVE_SOURCE',
    evidenceTier: 'PRIMARY_SOURCE',
    isVerbatimText: true,
    effectiveDate: '2019-04-01',
    verbatimStatuteText: 'Salary earned by an employee under a contract of service shall be paid before the expiry of the seventh day after the last day of the salary period. Payment for overtime work shall be made within 14 days after the end of the salary period.'
  },

  MOM_SEC22_PRORATED_SALARY: {
    id: 'MOM_SEC22_PRORATED_SALARY',
    authority: 'MOM',
    authorityName: 'Ministry of Manpower (MOM)',
    sourcePublisher: 'Singapore Statutes Online / AGC',
    legalOrStandardInstrument: 'Employment Act 1968',
    actTitle: 'Employment Act 1968',
    actCode: 'EA1968',
    sectionOrSchedule: 'Section 22',
    ruleTitle: 'MOM Formula for Salary Computation for Incomplete Month of Work',
    category: 'MOM_LABOUR',
    principle: 'Under Section 22 of the Employment Act 1968, salary for an incomplete month of service (commencement, resignation, or termination) is calculated as: (Monthly Basic Salary / Total Working Days in Month) x Total Working Days Worked.',
    application: 'Prorated salary calculation on resignation or termination. Total working days and days worked exclude rest days and non-working days for a 5-day work week.',
    practicalRules: [
      'Formula: Gross Salary Payable = (Monthly Basic Rate of Pay / Total Working Days in Month) * Actual Days Worked.',
      'Total Working Days: Number of days on which employee was required to work in that month (excludes rest days / non-working Saturdays/Sundays).',
      'Payment Deadline: On employee resignation with notice, full salary and benefits must be paid on the employee\'s last day of employment (Section 21(2)).'
    ],
    canonicalUrl: 'https://sso.agc.gov.sg/Act/EmA1968?ProvIds=P13-#pr22-',
    tags: ['prorated salary', 'incomplete month', 'section 22', 'last day', 'resignation salary', 'mom formula', 'salary proration'],
    sourceStatus: 'VERIFIED',
    sourceType: 'AUTHORITATIVE_SOURCE',
    evidenceTier: 'PRIMARY_SOURCE',
    isVerbatimText: true,
    effectiveDate: '2019-04-01',
    verbatimStatuteText: 'The salary payable to an employee for an incomplete month of work shall be calculated in accordance with the formula: (Monthly basic rate of pay / Total number of working days in that month) x Total number of days on which the employee was required to work and actually worked.'
  },

  // -------------------------------------------------------------

  // -------------------------------------------------------------
  MOM_SEC88A_ANNUAL_LEAVE: {
    id: 'MOM_SEC88A_ANNUAL_LEAVE',
    authority: 'MOM',
    authorityName: 'Ministry of Manpower (MOM)',
    sourcePublisher: 'Singapore Statutes Online / AGC',
    legalOrStandardInstrument: 'Employment Act 1968',
    actTitle: 'Employment Act 1968',
    actCode: 'EA1968',
    sectionOrSchedule: 'Section 88A',
    ruleTitle: 'Paid Annual Leave Statutory Entitlements (7 to 14 Days)',
    category: 'MOM_LABOUR',
    principle: 'An employee who has served an employer for a period of not less than 3 months shall be entitled to paid annual leave of 7 days in respect of the first 12 months of continuous service with that employer, and an additional one day of paid annual leave for every subsequent 12 months of continuous service, up to a maximum of 14 days.',
    verbatimStatuteText: 'An employee who has served an employer for a period of not less than 3 months shall be entitled to paid annual leave of 7 days in respect of the first 12 months of continuous service with the employer and an additional one day’s paid annual leave for every subsequent 12 months of continuous service with the same employer, subject to a maximum of 14 days of paid annual leave.',
    application: 'Leave administration and payroll accrual calculations for permanent and contract employees.',
    practicalRules: [
      'Paid Annual Leave (Section 88A): Minimum 7 days after 1 year of service, increasing by 1 additional day per completed year of service, up to a statutory maximum of 14 days for 8 or more years of service.',
      'Pro-rating: Employees who have served at least 3 months in a calendar year are entitled to pro-rated annual leave in that year.',
      'Forfeiture / Encashment: Statutory annual leave cannot be unlawfully forfeited if statutory qualification criteria are met.'
    ],
    canonicalUrl: 'https://sso.agc.gov.sg/Act/EmA1968?ProvIds=P110-#pr88A-',
    tags: ['annual leave', 'section 88a', 'leave entitlement', '7 days', '14 days', 'statutory annual leave'],
    sourceStatus: 'VERIFIED',
    sourceType: 'AUTHORITATIVE_SOURCE',
    evidenceTier: 'PRIMARY_SOURCE',
    isVerbatimText: true,
    effectiveDate: '2019-04-01'
  },

  MOM_SEC89_SICK_LEAVE: {
    id: 'MOM_SEC89_SICK_LEAVE',
    authority: 'MOM',
    authorityName: 'Ministry of Manpower (MOM)',
    sourcePublisher: 'Singapore Statutes Online / AGC',
    legalOrStandardInstrument: 'Employment Act 1968',
    actTitle: 'Employment Act 1968',
    actCode: 'EA1968',
    sectionOrSchedule: 'Section 89',
    ruleTitle: 'Paid Outpatient Sick Leave (14 Days) and Hospitalisation Leave (60 Days)',
    category: 'MOM_LABOUR',
    principle: 'An employee who has served an employer for a period of not less than 3 months is entitled to paid sick leave not exceeding 14 days in each year if no hospitalisation is necessary, or 60 days in each year if hospitalisation is necessary.',
    verbatimStatuteText: 'An employee who has served an employer for a period of not less than 3 months is entitled to paid sick leave (including paid medical examination leave) not exceeding in the aggregate — (a) 14 days in each year if no hospitalisation is necessary; or (b) 60 days in each year if hospitalisation is necessary (including the 14 days of outpatient sick leave).',
    application: 'Paid medical leave and hospitalisation leave administration.',
    practicalRules: [
      'Paid Outpatient Sick Leave (Section 89): Up to 14 days per calendar year if certified by an approved medical practitioner. Graduated during first 6 months (5 days at 3 months, 8 days at 4 months, 11 days at 5 months, 14 days at 6+ months).',
      'Paid Hospitalisation Leave (Section 89): Up to 60 days per calendar year (inclusive of the 14 days of outpatient sick leave).',
      'Medical Certification: Medical certificates must be issued by a registered medical practitioner or company-appointed doctor.'
    ],
    canonicalUrl: 'https://sso.agc.gov.sg/Act/EmA1968?ProvIds=P110-#pr89-',
    tags: ['sick leave', 'outpatient sick leave', 'hospitalisation leave', 'section 89', 'medical leave', '14 days'],
    sourceStatus: 'VERIFIED',
    sourceType: 'AUTHORITATIVE_SOURCE',
    evidenceTier: 'PRIMARY_SOURCE',
    isVerbatimText: true,
    effectiveDate: '2019-04-01'
  },

  MOM_SEC38_OVERTIME: {
    id: 'MOM_SEC38_OVERTIME',
    authority: 'MOM',
    authorityName: 'Ministry of Manpower (MOM)',
    sourcePublisher: 'Singapore Statutes Online / AGC',
    legalOrStandardInstrument: 'Employment Act 1968',
    actTitle: 'Employment Act 1968',
    actCode: 'EA1968',
    sectionOrSchedule: 'Section 38',
    ruleTitle: 'Part IV Hours of Work, Overtime Rate (1.5x Hourly Rate) & 72-Hour Monthly Cap',
    category: 'MOM_LABOUR',
    principle: 'For any overtime work, the employer shall pay the employee at the rate of not less than 1-1/2 times the employee’s hourly basic rate of pay. An employee shall not be permitted to work overtime for more than 72 hours a month without an MOM exemption.',
    verbatimStatuteText: 'For any overtime work, the employer shall pay the employee at the rate of not less than 1-1/2 times the employee’s hourly basic rate of pay. An employee shall not be permitted to work overtime for more than 72 hours a month, or such other number of hours as the Minister may prescribe.',
    application: 'Payroll calculation for overtime hours worked by Part IV eligible employees.',
    practicalRules: [
      'Coverage Threshold: Non-workmen earning monthly basic salary $\\le$ SGD 2,600; Workmen earning $\\le$ SGD 4,500.',
      'Overtime Rate: At least 1.5 times the hourly basic rate of pay (for non-workmen, salary capped at SGD 2,600 or SGD 13.60/hour for calculation).',
      'Maximum Overtime Cap: An employee cannot work more than 72 hours of overtime in a calendar month, except with an MOM overtime exemption.',
      'Payment Deadline: Under Section 21, overtime payment must be disbursed within 14 days after the end of the salary period.'
    ],
    canonicalUrl: 'https://sso.agc.gov.sg/Act/EmA1968?ProvIds=P14-#pr38-',
    tags: ['overtime', 'overtime rate', '1.5x', 'part iv', 'overtime pay', 'working hours', 'section 38', '72 hours'],
    sourceStatus: 'VERIFIED',
    sourceType: 'AUTHORITATIVE_SOURCE',
    evidenceTier: 'PRIMARY_SOURCE',
    isVerbatimText: true,
    effectiveDate: '2019-04-01'
  },

  MOM_ANNUAL_SICK_LEAVE: {
    id: 'MOM_ANNUAL_SICK_LEAVE',
    authority: 'MOM',
    authorityName: 'Ministry of Manpower (MOM)',
    sourcePublisher: 'Singapore Statutes Online / AGC',
    legalOrStandardInstrument: 'Employment Act 1968',
    actTitle: 'Employment Act 1968',
    actCode: 'EA1968',
    sectionOrSchedule: 'Section 88A & Section 89',
    ruleTitle: 'Annual Leave and Paid Sick / Hospitalisation Leave Statutory Entitlements',
    category: 'MOM_LABOUR',
    principle: 'Employees covered by the Employment Act who have served an employer for at least 3 months are entitled to paid sick leave. Employees who have served for at least 12 months are entitled to statutory paid annual leave.',
    verbatimStatuteText: 'An employee who has served an employer for a period of not less than 3 months shall be entitled to paid annual leave of 7 days in respect of the first 12 months of continuous service with the employer and an additional one day’s paid annual leave for every subsequent 12 months of continuous service with the same employer, subject to a maximum of 14 days of paid annual leave. An employee who has served for at least 3 months is entitled to paid sick leave not exceeding 14 days if no hospitalisation is necessary, or 60 days if hospitalisation is necessary.',
    application: 'Leave administration and payroll accrual calculations for permanent and contract employees.',
    practicalRules: [
      'Paid Annual Leave (Section 88A): Minimum 7 days after 1 year of service, increasing by 1 additional day per completed year of service, up to a statutory maximum of 14 days for 8 or more years of service.',
      'Paid Outpatient Sick Leave (Section 89): Up to 14 days per calendar year if certified by an approved medical practitioner. Graduated during first 6 months of employment (5 days at 3 months, 8 days at 4 months, 11 days at 5 months, 14 days at 6+ months).',
      'Paid Hospitalisation Leave (Section 89): Up to 60 days per calendar year (which includes the 14 days of outpatient sick leave).',
      'Public Holidays (Section 88): 11 statutory gazetted public holidays per year. If required to work on a public holiday, an employee is entitled to an extra day of basic salary or a day off in lieu.'
    ],
    canonicalUrl: 'https://sso.agc.gov.sg/Act/EmA1968?ProvIds=P110-#pr89-',
    tags: ['annual leave', 'sick leave', 'hospitalisation leave', 'leave entitlement', 'public holiday', 'section 89', 'employment act leave'],
    sourceStatus: 'VERIFIED',
    sourceType: 'AUTHORITATIVE_SOURCE',
    evidenceTier: 'PRIMARY_SOURCE',
    isVerbatimText: true,
    effectiveDate: '2019-04-01'
  },

  MOM_OVERTIME_PART_IV: {
    id: 'MOM_OVERTIME_PART_IV',
    authority: 'MOM',
    authorityName: 'Ministry of Manpower (MOM)',
    sourcePublisher: 'Singapore Statutes Online / AGC',
    legalOrStandardInstrument: 'Employment Act 1968',
    actTitle: 'Employment Act 1968',
    actCode: 'EA1968',
    sectionOrSchedule: 'Section 38',
    ruleTitle: 'Part IV Working Hours, Overtime Limits & Overtime Pay Rate (1.5x Hourly Rate)',
    category: 'MOM_LABOUR',
    principle: 'Part IV of the Employment Act protects workmen earning up to $4,500/month and non-workmen earning up to $2,600/month. Hours worked beyond contractual standard hours (max 44 hours/week) must be paid at overtime rates.',
    verbatimStatuteText: 'For any overtime work, the employer shall pay the employee at the rate of not less than 1-1/2 times the employee’s hourly basic rate of pay. An employee shall not be permitted to work overtime for more than 72 hours a month, or such other number of hours as the Minister may prescribe.',
    application: 'Payroll calculation for overtime hours worked by eligible employees.',
    practicalRules: [
      'Coverage Threshold: Non-workmen earning monthly basic salary $\\le$ SGD 2,600; Workmen earning $\\le$ SGD 4,500.',
      'Overtime Rate: At least 1.5 times the hourly basic rate of pay (for non-workmen, salary capped at SGD 2,600 or SGD 13.60/hour for calculation).',
      'Maximum Overtime Cap: An employee cannot work more than 72 hours of overtime in a calendar month, except with an MOM overtime exemption.',
      'Payment Deadline: Under Section 21, overtime payment must be disbursed within 14 days after the end of the salary period.'
    ],
    canonicalUrl: 'https://sso.agc.gov.sg/Act/EmA1968?ProvIds=P14-#pr38-',
    tags: ['overtime', 'overtime rate', '1.5x', 'part iv', 'overtime pay', 'working hours', 'section 38', '44 hours'],
    sourceStatus: 'VERIFIED',
    sourceType: 'AUTHORITATIVE_SOURCE',
    evidenceTier: 'PRIMARY_SOURCE',
    isVerbatimText: true,
    effectiveDate: '2019-04-01',
    validFrom: '2019-04-01',
    lastVerifiedDate: '2026-09-01',
    reviewAuditCycleDays: 365
  },

  MOM_SEC36_37_REST_DAY_PAY: {
    id: 'MOM_SEC36_37_REST_DAY_PAY',
    authority: 'MOM',
    authorityName: 'Ministry of Manpower (MOM)',
    sourcePublisher: 'Singapore Statutes Online / AGC',
    legalOrStandardInstrument: 'Employment Act 1968',
    actTitle: 'Employment Act 1968',
    actCode: 'EA1968',
    sectionOrSchedule: 'Section 36 & Section 37',
    ruleTitle: 'Rest Day Entitlement & Statutory Payment Computation for Work Done on Rest Day',
    category: 'MOM_LABOUR',
    principle: 'Under Sections 36 and 37 of the Employment Act 1968, an employer must allow each employee one rest day comprising a whole day without pay per week (§36). If an employee works on a rest day at the employer\'s request (§37(2)): for work not exceeding half the normal daily working hours, the employer must pay 1 full day\'s basic wage; for work exceeding half but not exceeding the normal daily working hours, the employer must pay 2 full days\' basic wages; for hours worked exceeding the normal daily hours, overtime is payable at not less than 1.5 times the hourly basic rate of pay (§37(3)). If work is at the employee\'s own request (§37(1)), the pay is half a day\'s wage for <= 0.5 day and 1 day\'s wage for <= 1 day.',
    verbatimStatuteText: 'Where an employee works on a rest day at the request of the employer, the employee shall be paid for work done on that day — (a) if the period of work does not exceed half the employee\'s normal daily hours of work, a sum at the basic rate of pay for one day\'s work; (b) if the period of work exceeds half but does not exceed the employee\'s normal daily hours of work, a sum at the basic rate of pay for 2 days\' work; or (c) if the period of work exceeds the employee\'s normal daily hours of work, a sum in accordance with paragraph (b) and an additional payment at a rate of not less than 1-1/2 times the hourly basic rate of pay.',
    application: 'Payroll calculation for employees required to work on Sunday or scheduled rest day: Basic rate of pay for 1 or 2 days plus 1.5x overtime.',
    practicalRules: [
      'Employer\'s Request: Work <= half normal shift: 1 full day\'s basic pay; Work > half normal shift: 2 full days\' basic pay.',
      'Overtime on Rest Day: Hours worked in excess of normal daily hours must be paid at >= 1.5 times the hourly basic rate.',
      'Employee\'s Request: Work <= half normal shift: 0.5 day\'s basic pay; Work > half normal shift: 1.0 day\'s basic pay.',
      'Part IV Coverage: Applies to workmen earning <= SGD 4,500 and non-workmen earning <= SGD 2,600.'
    ],
    canonicalUrl: 'https://sso.agc.gov.sg/Act/EmA1968?ProvIds=P14-#pr37-',
    tags: ['rest day pay', 'section 36', 'section 37', 'sunday work', 'rest day computation', '1 day pay', '2 days pay'],
    sourceStatus: 'VERIFIED',
    sourceType: 'AUTHORITATIVE_SOURCE',
    evidenceTier: 'PRIMARY_SOURCE',
    isVerbatimText: true,
    effectiveDate: '2019-04-01',
    validFrom: '2019-04-01',
    lastVerifiedDate: '2026-09-01',
    reviewAuditCycleDays: 365
  },

  MOM_MANDATORY_RETRENCHMENT_NOTIFICATION: {
    id: 'MOM_MANDATORY_RETRENCHMENT_NOTIFICATION',
    authority: 'MOM',
    authorityName: 'Ministry of Manpower (MOM)',
    sourcePublisher: 'Singapore Statutes Online / AGC',
    legalOrStandardInstrument: 'Employment Act 1968 & Employment (Retrenchment Notification) Regulations',
    actTitle: 'Employment Act 1968',
    actCode: 'EA1968',
    sectionOrSchedule: 'Section 96A & Retrenchment Notification Regulations',
    ruleTitle: 'Mandatory Retrenchment Notification (MRN) to MOM within 5 Working Days',
    category: 'MOM_LABOUR',
    principle: 'Under the Employment (Retrenchment Notification) Regulations and Section 96A of the Employment Act 1968, employers with 10 or more employees who retrench 5 or more employees within any 6-month period must submit a mandatory notification to the Ministry of Manpower (MOM) via the MyMOM portal within 5 working days after giving notice of retrenchment to affected employees.',
    verbatimStatuteText: 'An employer who employs 10 or more employees must notify the Commissioner for Labour of any retrenchment of employees within 5 working days after the employer gives notice of retrenchment to the affected employee, where the retrenchment is of 5 or more employees in any 6-month period.',
    application: 'Corporate restructuring, down-sizing, and redundancy exercises: Filing mandatory retrenchment returns to Workforce Singapore / MOM within 5 working days.',
    practicalRules: [
      'Employer Threshold: Business employing 10 or more employees in total.',
      'Trigger Threshold: Retrenchment of 5 or more employees within any 6-month rolling window.',
      'Filing Deadline: Within 5 working days of notifying affected staff.',
      'Penalties: Failure to notify is a civil penalty offence under Section 96A subject to administrative financial penalties up to SGD 2,000 per breach.'
    ],
    canonicalUrl: 'https://sso.agc.gov.sg/SL/EA1968-RG14',
    tags: ['retrenchment notification', 'mandatory retrenchment', 'section 96a', '5 employees 6 months', '5 working days'],
    sourceStatus: 'VERIFIED',
    sourceType: 'AUTHORITATIVE_SOURCE',
    evidenceTier: 'PRIMARY_SOURCE',
    isVerbatimText: true,
    effectiveDate: '2021-11-01',
    validFrom: '2021-11-01',
    lastVerifiedDate: '2026-09-01',
    reviewAuditCycleDays: 365
  },

  MOM_CDCA_PARENTAL_LEAVES: {
    id: 'MOM_CDCA_PARENTAL_LEAVES',
    authority: 'MOM',
    authorityName: 'Ministry of Manpower (MOM) & MSF',
    sourcePublisher: 'Singapore Statutes Online / AGC',
    legalOrStandardInstrument: 'Child Development Co-Savings Act 2001 & Employment Act 1968',
    actTitle: 'Child Development Co-Savings Act 2001',
    actCode: 'CDCA2001',
    sectionOrSchedule: 'Section 9, Section 12B & EA Section 87A',
    ruleTitle: 'Statutory Paid Maternity Leave (16 Weeks), Paternity Leave (4 Weeks) & Childcare Leave (6 Days)',
    category: 'MOM_LABOUR',
    principle: 'Under the Child Development Co-Savings Act 2001 and the Employment Act 1968, eligible working mothers of a Singapore Citizen child are entitled to 16 weeks of Government-Paid Maternity Leave (GPML). Eligible working fathers are entitled to 4 weeks of Government-Paid Paternity Leave (GPPL). Working parents of a Singapore Citizen child aged below 7 years are each entitled to 6 days of paid childcare leave per year.',
    verbatimStatuteText: 'Subject to this section, every female employee who has served an employer for a period of not less than 3 months shall be entitled to absent herself from work during periods prescribed as maternity leave for a total of 16 weeks, and every male employee who has served an employer for not less than 3 months shall be entitled to paternity leave of 4 weeks.',
    application: 'Payroll administration and government-paid claims via the GPL portal (pro-family leave reimbursement for employers).',
    practicalRules: [
      'Maternity Leave (16 Weeks): For 1st & 2nd child: 8 weeks employer-funded + 8 weeks government-funded. For 3rd+ child: all 16 weeks government-funded (capped at SGD 10,000 per 4-week block).',
      'Paternity Leave (4 Weeks): Mandatory 4 weeks government-paid paternity leave for working fathers of Singapore citizen children (effective 1 Jan 2024).',
      'Childcare Leave: 6 days per parent per year for children under 7 years (first 3 days employer-funded, next 3 days government-funded).',
      'Service Requirement: Employee must have served the employer for at least 3 continuous months prior to child\'s birth.'
    ],
    canonicalUrl: 'https://sso.agc.gov.sg/Act/CDCSA2001?ProvIds=P13-#pr9-',
    tags: ['maternity leave 16 weeks', 'paternity leave 4 weeks', 'childcare leave 6 days', 'cdca 2001', 'parental leave', 'government paid'],
    sourceStatus: 'VERIFIED',
    sourceType: 'AUTHORITATIVE_SOURCE',
    evidenceTier: 'PRIMARY_SOURCE',
    isVerbatimText: true,
    effectiveDate: '2024-01-01',
    validFrom: '2024-01-01',
    lastVerifiedDate: '2026-09-01',
    reviewAuditCycleDays: 365
  },

  // -------------------------------------------------------------
};
